ansible-collections/cisco.ios

- README.rst
- galaxy.yml
New information on repo home and fix incorrect readme file.
> Update galaxy.yml and README.rst

- plugins/module_utils/network/ios/argspec/l2_interfaces/l2_interfaces.py
- plugins/module_utils/network/ios/config/l2_interfaces/l2_interfaces.py
- plugins/module_utils/network/ios/facts/l2_interfaces/l2_interfaces.py
- plugins/modules/ios_l2_interfaces.py
- tests/integration/targets/ios_l2_interfaces/vars/main.yaml
Signed-off-by: CaptTrews <capttrews@gmail.com>
> Updated from network content collector

- galaxy.yml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/357
> Add ansible.netcommon dependency

- .yamllint
- .zuul.yaml
- test-requirements.txt
- tox.ini
> Enable yamllint validation

- plugins/module_utils/network/ios/config/acls/acls.py
- plugins/module_utils/network/ios/utils/utils.py
To fix ios_acl py35 idempotent issue bug raised in issue: #9 
ios_acls
```paste below
```
> To fix ios_acl py35 idempotent issue

- galaxy.yml
> Update galaxy.yml repo location

- README.md
- README.rst
- galaxy.yml
documentation
```paste below
```
> update IOS readme

- plugins/module_utils/network/ios/config/l2_interfaces/l2_interfaces.py
- tests/integration/targets/ios_l2_interfaces/tests/cli/_remove_vlan_config.yaml
- tests/integration/targets/ios_l2_interfaces/tests/cli/deleted.yaml
- tests/integration/targets/ios_l2_interfaces/tests/cli/merged.yaml
- tests/integration/targets/ios_l2_interfaces/tests/cli/overridden.yaml
- tests/integration/targets/ios_l2_interfaces/tests/cli/replaced.yaml
- tests/integration/targets/ios_l2_interfaces/vars/main.yaml
To Fix the merge behaving as replace/override in `ios_l2_interfaces` resource raised in #26 
ios_l2_interfaces
```paste below
```
> To Fix the merge behaving as replace/override in ios_l2_interfaces resource

- plugins/module_utils/network/ios/argspec/lacp_interfaces/lacp_interfaces.py
- plugins/module_utils/network/ios/config/lacp_interfaces/lacp_interfaces.py
- plugins/modules/ios_lacp_interfaces.py
- tests/integration/targets/ios_lacp_interfaces/tests/cli/_parsed.cfg
- tests/integration/targets/ios_lacp_interfaces/tests/cli/empty_config.yaml
- tests/integration/targets/ios_lacp_interfaces/tests/cli/gathered.yaml
- tests/integration/targets/ios_lacp_interfaces/tests/cli/parsed.yaml
- tests/integration/targets/ios_lacp_interfaces/tests/cli/rendered.yaml
- tests/integration/targets/ios_lacp_interfaces/tests/cli/rtt.yaml
- tests/integration/targets/ios_lacp_interfaces/vars/main.yaml
Adding new supported states to Ios_lacp_interfaces resource module
ios_lacp_interfaces
```paste below
```
> Adding new supported states to Ios_lacp_interfaces resource module

- plugins/module_utils/network/ios/argspec/lacp/lacp.py
- plugins/module_utils/network/ios/config/lacp/lacp.py
- plugins/modules/ios_lacp.py
- tests/integration/targets/ios_lacp/tests/cli/_parsed.cfg
- tests/integration/targets/ios_lacp/tests/cli/empty_config.yaml
- tests/integration/targets/ios_lacp/tests/cli/gathered.yaml
- tests/integration/targets/ios_lacp/tests/cli/parsed.yaml
- tests/integration/targets/ios_lacp/tests/cli/rendered.yaml
- tests/integration/targets/ios_lacp/vars/main.yaml
Adding new supported states to LACP resource module 
ios_lacp
```paste below
```
> Adding new supported states to LACP resource module 

- plugins/module_utils/network/ios/argspec/lldp_global/lldp_global.py
- plugins/module_utils/network/ios/config/lldp_global/lldp_global.py
- plugins/module_utils/network/ios/facts/lldp_global/lldp_global.py
- plugins/modules/ios_lldp_global.py
- tests/integration/targets/ios_lldp_global/tests/cli/_parsed.cfg
- tests/integration/targets/ios_lldp_global/tests/cli/empty_config.yaml
- tests/integration/targets/ios_lldp_global/tests/cli/gathered.yaml
- tests/integration/targets/ios_lldp_global/tests/cli/parsed.yaml
- tests/integration/targets/ios_lldp_global/tests/cli/rendered.yaml
- tests/integration/targets/ios_lldp_global/vars/main.yaml
Adding new supported states to Ios_lldp_global resource module
- Feature Pull Reques
ios_lldp_global
```paste below
```
> Adding new supported states to Ios_lldp_global resource module

- plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py
- plugins/modules/ios_acl_interfaces.py
- tests/integration/targets/ios_acl_interfaces/tests/cli/deleted.yaml
- tests/integration/targets/ios_acl_interfaces/vars/main.yaml
- tests/unit/modules/network/ios/test_ios_acl_interfaces.py
Update and Comment IOS ACL interfaces granular delete operation
ios_acl_interfaces
```paste below
```
> Update and Comment IOS ACL interfaces granular delete operation

- plugins/module_utils/network/ios/config/acls/acls.py
- plugins/modules/ios_acls.py
- tests/integration/targets/ios_acls/tests/cli/deleted.yaml
- tests/integration/targets/ios_acls/vars/main.yaml
Update and Fix IOS ACLs granular delete operation
ios_acls
```paste below
```
> Update and Fix IOS ACLs granular delete operation

- plugins/modules/ios_command.py
fix ios_command document.  https://github.com/ansible-collections/cisco.ios/issues/53
ios_command 
```paste below
```
> ios_command: fix doc

- plugins/module_utils/network/ios/argspec/vlans/vlans.py
- plugins/module_utils/network/ios/config/vlans/vlans.py
- plugins/module_utils/network/ios/facts/vlans/vlans.py
- plugins/modules/ios_vlans.py
- tests/integration/targets/ios_vlans/tests/cli/_parsed.cfg
- tests/integration/targets/ios_vlans/tests/cli/empty_config.yaml
- tests/integration/targets/ios_vlans/tests/cli/gathered.yaml
- tests/integration/targets/ios_vlans/tests/cli/parsed.yaml
- tests/integration/targets/ios_vlans/tests/cli/rendered.yaml
- tests/integration/targets/ios_vlans/tests/cli/rtt.yaml
- tests/integration/targets/ios_vlans/vars/main.yaml
Adding new supported states to Ios_vlans resource module
ios_vlans
```paste below
```
> Adding new supported states to Ios_vlans resource module

- plugins/module_utils/network/ios/argspec/interfaces/interfaces.py
- plugins/module_utils/network/ios/config/interfaces/interfaces.py
- plugins/module_utils/network/ios/facts/interfaces/interfaces.py
- plugins/modules/ios_interfaces.py
- tests/integration/targets/ios_interfaces/tests/cli/_parsed.cfg
- tests/integration/targets/ios_interfaces/tests/cli/empty_config.yaml
- tests/integration/targets/ios_interfaces/tests/cli/gathered.yaml
- tests/integration/targets/ios_interfaces/tests/cli/parsed.yaml
- tests/integration/targets/ios_interfaces/tests/cli/rendered.yaml
- tests/integration/targets/ios_interfaces/vars/main.yaml
Adding new supported states to Ios_interfaces resource module
ios_interfaces
```paste below
```
> Adding new supported states to Ios_interfaces resource module

- plugins/module_utils/network/ios/argspec/l3_interfaces/l3_interfaces.py
- plugins/module_utils/network/ios/config/l3_interfaces/l3_interfaces.py
- plugins/module_utils/network/ios/facts/l3_interfaces/l3_interfaces.py
- plugins/module_utils/network/ios/utils/utils.py
- plugins/modules/ios_l3_interfaces.py
- tests/integration/targets/ios_l3_interfaces/tests/cli/_parsed.cfg
- tests/integration/targets/ios_l3_interfaces/tests/cli/empty_config.yaml
- tests/integration/targets/ios_l3_interfaces/tests/cli/gathered.yaml
- tests/integration/targets/ios_l3_interfaces/tests/cli/parsed.yaml
- tests/integration/targets/ios_l3_interfaces/tests/cli/rendered.yaml
- tests/integration/targets/ios_l3_interfaces/tests/cli/rtt.yaml
- tests/integration/targets/ios_l3_interfaces/vars/main.yaml
Adding new supported states to Ios_l3_interfaces resource module
ios_l3_interfaces
```paste below
```
> Adding new supported states to Ios_l3_interfaces resource module

- test-requirements.txt
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>
Add test requirement coverage==4.5.4
> [cisco.ios] Add test requirement for coverage

- README.md
> added contributor guide link etc

- tests/integration/targets/ios_smoke/defaults/main.yaml
- tests/integration/targets/ios_smoke/meta/main.yaml
- tests/integration/targets/ios_smoke/tasks/cli.yaml
- tests/integration/targets/ios_smoke/tasks/main.yaml
- tests/integration/targets/ios_smoke/templates/defaults/config.j2
- tests/integration/targets/ios_smoke/tests/cli/common_config.yaml
- tests/integration/targets/ios_smoke/tests/cli/common_utils.yaml
- tests/integration/targets/ios_smoke/tests/cli/misc_tests.yaml
Add missing ios_smoke tests to IOS colletion
ios_smoke
```paste below
```
> Add missing ios_smoke tests to IOS colletion

- meta/runtime.yml
*  Add `removal_date` and `warning_text` keys for deprecated
plugins
*  Add missing modules in redirection
meta/runtime.yml
```paste below
```
> Update runtime meta file

- README.md
> Clean up reference of master to main

- docs/cisco.ios.ios_l3_interfaces_module.rst
- docs/cisco.ios.ios_lldp_global_module.rst
- plugins/modules/ios_l3_interfaces.py
- plugins/modules/ios_lldp_global.py
fix the OS name from Vyos to IOS
- ios_l3_interfaces_module
- ios_lldp_global_module
```paste below
```
> fix OS name

- changelogs/CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1.1.0_update_docs.yaml
- changelogs/fragments/90-add-change-log-1.0.0.yaml
- changelogs/fragments/handle_src_backup_with_module_alias.yaml
- changelogs/fragments/remove_ios_ignore.yaml
Update IOS changelog
ios
```paste below
```
> Update IOS changelog

- galaxy.yml
To fix description typo under galaxy yaml
cisco.ios
```paste below
```
> To fix description typo under galaxy yaml

- changelogs/fragments/103_fix_l2_interfaces_traceback_error.yaml
- plugins/module_utils/network/ios/config/l2_interfaces/l2_interfaces.py
- plugins/module_utils/network/ios/facts/l2_interfaces/l2_interfaces.py
- plugins/module_utils/network/ios/utils/utils.py
- plugins/modules/ios_l2_interfaces.py
- tests/unit/modules/network/ios/fixtures/ios_l2_interfaces.cfg
- tests/unit/modules/network/ios/test_ios_l2_interfaces.py
To fix IOS l2 interfaces for traceback error and merge operation not working as expected raised in bug #44 and #77 .
ios_l2_interfaces
```paste below
```
> To fix IOS l2 interfaces for traceback error and merge operation not working as expected

- changelogs/CHANGELOG.rst
To update changelog with bugfix that'll not get merged when tagging for 1.0.3
changelog.rst
```paste below
```
> To update changelog with bugfix that'll not get merged when tagging for 1.0.3

- changelogs/fragments/141_add_int_virt_template_issue.yml
- plugins/module_utils/network/ios/utils/utils.py
Resolves: #141
```paste below
```
> Add support for interface type Virtual-Template

- changelogs/fragments/command-dicts.yaml
- plugins/modules/ios_command.py
Fixes #140
ios_command
```paste below
```
> Fix element type of ios_command's command parameter

- README.md
- changelogs/CHANGELOG.rst
- changelogs/changelog.yaml
- docs/cisco.ios.ios_command_module.rst
- docs/cisco.ios.ios_l2_interfaces_module.rst
- docs/cisco.ios.ios_ospfv3_module.rst
IOS collection prep for v1.1.0 tagging
ios
```paste below
```
> IOS collection prep for v1.1.0 tagging

- changelogs/fragments/209_fix_ios_ospf_interfaces_authentication_param.yaml
- plugins/module_utils/network/ios/argspec/ospf_interfaces/ospf_interfaces.py
- plugins/module_utils/network/ios/rm_templates/ospf_interfaces.py
- plugins/modules/ios_ospf_interfaces.py
- tests/integration/targets/ios_ospf_interfaces/tests/cli/_parsed.cfg
- tests/integration/targets/ios_ospf_interfaces/tests/cli/_populate_config.yaml
- tests/integration/targets/ios_ospf_interfaces/tests/cli/merged.yaml
- tests/integration/targets/ios_ospf_interfaces/tests/cli/rendered.yaml
- tests/integration/targets/ios_ospf_interfaces/tests/cli/rtt.yaml
- tests/integration/targets/ios_ospf_interfaces/vars/main.yaml
- tests/unit/modules/network/ios/test_ios_ospf_interfaces.py
To fix ios_ospf_interfaces authentication behavior where respective params config was not getting configured as expected. Fixes #209 
ios_ospf_interfaces
```paste below
```
> To fix ios_ospf_interfaces authentication behaviour where respective params config was not getting configured as expected

- changelogs/fragments/ios_config_diff_doc_update.yaml
- plugins/modules/ios_config.py
FIxes https://github.com/ansible-collections/ansible.netcommon/issues/189
*  Update doc
*  Add warning message for idempotent pre-requisite
ios_config
```paste below
```
> Update doc to clarify on input config pattern

- .zuul.yaml
- changelogs/fragments/165_enable_ospfv3_integration_tests.yaml
- changelogs/fragments/upcap_ansible.yaml
- meta/runtime.yml
- plugins/module_utils/network/ios/ios.py
- plugins/modules/ios_l2_interface.py
- plugins/modules/ios_l3_interface.py
- plugins/modules/ios_vlan.py
- tests/sanity/ignore-2.11.txt
This commit starts the process to start using EEs to manage our testing
needs.
> Updates needed for execution environments

- changelogs/fragments/223_fix_static_routes_facts_parsing.yaml
- plugins/module_utils/network/ios/facts/static_routes/static_routes.py
- plugins/module_utils/network/ios/utils/utils.py
- tests/integration/targets/ios_static_routes/tests/cli/merged.yaml
- tests/integration/targets/ios_static_routes/vars/main.yaml
- tests/unit/modules/network/ios/fixtures/ios_static_routes_config.cfg
- tests/unit/modules/network/ios/test_ios_static_routes.py
To fix ios_static_routes facts parsing in presence of interface. Fixes #223 
```paste below
```
> To fix ios_static_routes facts parsing in presence of interface

- changelogs/fragments/update_resource_module_doc_discrepancy.yaml
- plugins/module_utils/network/ios/facts/ospfv2/ospfv2.py
- plugins/modules/ios_acls.py
- plugins/modules/ios_bgp_global.py
- plugins/modules/ios_ospfv2.py
- plugins/modules/ios_static_routes.py
IOS resource modules minor doc updates
ios_bgp_global
ios_acls
ios_ospfv2
```paste below
```
> IOS resource modules minor doc updates

- changelogs/fragments/unittest_fix_for_resource_module_base.yaml
- tests/unit/modules/network/ios/test_ios_acls.py
- tests/unit/modules/network/ios/test_ios_bgp_global.py
- tests/unit/modules/network/ios/test_ios_ospf_interfaces.py
- tests/unit/modules/network/ios/test_ios_ospfv2.py
- tests/unit/modules/network/ios/test_ios_ospfv3.py
Depends-On: ansible-collections/ansible.netcommon#180
Fix Unit test cases for new resource_module_base class
ios UTs
```paste below
```
> Fix unit test for resource_module_base

- changelogs/fragments/242_ios_acls_parsed_doc_fix.yml
- plugins/modules/ios_acls.py
To fix `ios_acls` parsed state example under module doc. Fixes #242 
`ios_acls`
```paste below
```
> To fix ios_acls parsed state example under module doc

- changelogs/fragments/261-remove_tests_sanity_requirements.yml
- tests/sanity/requirements.txt
https://github.com/ansible-collections/overview/issues/43
> Remove tests/sanity/requirements.txt

- changelogs/fragments/190_fix_ios_acls_log_loginput_param.yaml
- plugins/module_utils/network/ios/argspec/acls/acls.py
- plugins/module_utils/network/ios/rm_templates/acls.py
- plugins/modules/ios_acls.py
- tests/unit/modules/network/ios/fixtures/ios_acls_config.cfg
- tests/unit/modules/network/ios/test_ios_acls.py
To fix ios_acls log and log_input params. Fixes #190 
ios_acls
```paste below
```
> To fix ios_acls log and log_input params

- changelogs/fragments/replace-check_required.yaml
- docs/cisco.ios.ios_acls_module.rst
- plugins/modules/ios_logging.py
- plugins/modules/ios_static_route.py
- tests/sanity/ignore-2.11.txt
> Replace removed module._check_required_* calls

- CHANGELOG.rst
- changelogs/changelog.yaml
- docs/cisco.ios.ios_logging_module.rst
- plugins/modules/ios_logging.py
IOS collection prep for v2.0.1 tagging
ios
```paste below
```
> IOS collection prep for v2.0.1 tagging

- plugins/modules/ios_lldp_interfaces.py
fix example deletion with interface.
The interface that was supposed to be changed was wrong.
- `cisco.ios.ios_lldp_interfaces`
> fix example deletion with interface

- changelogs/fragments/255_fix_wrong_arg_in_acls_template.yaml
- plugins/module_utils/network/ios/config/acls/acls.py
- plugins/module_utils/network/ios/rm_templates/acls.py
- tests/unit/modules/network/ios/test_ios_acls.py
To fix the wrong arg being passed in acls template function. Fixes #255
ios_acls
```paste below
```
> To fix the wrong arg being passed in acls template function

- changelogs/fragments/282_available_network_resources_support.yaml
- plugins/module_utils/network/ios/argspec/facts/facts.py
- plugins/modules/ios_facts.py
- tests/integration/targets/ios_facts/tests/cli/all_facts.yaml
Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>
Targets: https://github.com/ansible-collections/cisco.ios/issues/282
ios_facts
How to use: refer https://github.com/ansible-collections/cisco.ios/issues/282
```paste below
```
> IOS: available_network_resources key implementation in ios_facts 

- changelogs/fragments/250_ios_acls_overridden_replaced_inconsistent_behaviour.yaml
- plugins/module_utils/network/ios/argspec/acls/acls.py
- plugins/module_utils/network/ios/config/acls/acls.py
- plugins/module_utils/network/ios/facts/acls/acls.py
- tests/integration/targets/ios_acls/tests/cli/overridden.yaml
- tests/integration/targets/ios_acls/tests/cli/replaced.yaml
- tests/integration/targets/ios_acls/tests/cli/rtt.yaml
- tests/integration/targets/ios_acls/vars/main.yaml
- tests/unit/modules/network/ios/test_ios_acls.py
To fix ios_acls overridden n replaced inconsistent behaviour. Fixes #250 and #226
ios_acls
```paste below
```
> To fix ios_acls overridden n replaced inconsistent behaviour

- changelogs/fragments/329_330_fix_doc.yaml
- plugins/modules/ios_acls.py
- plugins/modules/ios_interfaces.py
fix after state example  with `state: replaced` and `state: overridden`.
> [ios_interfaces] fix after state

- README.md
- changelogs/fragments/readme_freenode_to_liberachat.yml
https://github.com/ansible-community/community-topics/issues/19
README
> Update README: freenode -> libera.chat

- changelogs/fragments/339_fix_acls_og_source_destination.yaml
- plugins/module_utils/network/ios/argspec/acls/acls.py
- plugins/module_utils/network/ios/config/acls/acls.py
- plugins/module_utils/network/ios/rm_templates/acls.py
- plugins/modules/ios_acls.py
- tests/integration/targets/ios_acls/vars/main.yaml
- tests/unit/modules/network/ios/fixtures/ios_acls_config.cfg
- tests/unit/modules/network/ios/test_ios_acls.py
PR to add the implementation of object group param to acls source and destination parameters. Fixes #339 
ios_acls
```paste below
```
> PR to add the implementation of object group param to acls source and destination parameters

- changelogs/fragments/336_add_updated_passive_interfaces_ospfv2.yaml
- plugins/module_utils/network/ios/argspec/ospfv2/ospfv2.py
- plugins/module_utils/network/ios/config/ospfv2/ospfv2.py
- plugins/module_utils/network/ios/facts/ospfv2/ospfv2.py
- plugins/module_utils/network/ios/rm_templates/ospfv2.py
- plugins/modules/ios_ospfv2.py
- tests/unit/modules/network/ios/fixtures/ios_ospfv2.cfg
- tests/unit/modules/network/ios/test_ios_ospfv2.py
To update ios ospfv2 passive_interface implementation to suppress/unsupress interface at the same time. Fixes #336 
ios_ospfv2
```paste below
```
> To update ios ospfv2 passive_interface implementation

- changelogs/fragments/355_l3_interace_fix.yaml
- docs/cisco.ios.ios_l3_interfaces_module.rst
- plugins/module_utils/network/ios/facts/l3_interfaces/l3_interfaces.py
- plugins/module_utils/network/ios/ios.py
- plugins/module_utils/network/ios/utils/utils.py
- tests/unit/modules/network/ios/fixtures/ios_l3_interfaces.cfg
- tests/unit/modules/network/ios/test_ios_l3_interfaces.py
fix #350
l3_interface serial interface fix and UT for l3
l2_interface
> l3_interface serial interface fix

- .gitignore
- changelogs/fragments/depricated_next_hop_self_bgpAddFamilt.yaml
- docs/cisco.ios.ios_bgp_address_family_module.rst
- plugins/module_utils/network/ios/argspec/bgp_address_family/bgp_address_family.py
- plugins/module_utils/network/ios/config/bgp_address_family/bgp_address_family.py
- plugins/module_utils/network/ios/rm_templates/bgp_address_family.py
- plugins/modules/ios_bgp_address_family.py
- tests/unit/modules/network/ios/test_ios_bgp_address_family.py
deprecate ios_bgp_address_family next_hop_self and add a new attribute for dict type
ios_bgp_address_family
> deprecate ios_bgp_address_family next_hop_self and add a new attribute for dict type

- changelogs/fragments/267_update_bgp_af_prefix_lists_route_maps_params.yaml
- plugins/module_utils/network/ios/argspec/bgp_address_family/bgp_address_family.py
- plugins/module_utils/network/ios/config/bgp_address_family/bgp_address_family.py
- plugins/module_utils/network/ios/facts/bgp_address_family/bgp_address_family.py
- plugins/module_utils/network/ios/rm_templates/bgp_address_family.py
- plugins/modules/ios_bgp_address_family.py
- tests/integration/targets/ios_bgp_address_family/tests/cli/_populate_config.yaml
- tests/integration/targets/ios_bgp_address_family/tests/cli/merged.yaml
- tests/integration/targets/ios_bgp_address_family/tests/cli/overridden.yaml
- tests/integration/targets/ios_bgp_address_family/tests/cli/rendered.yaml
- tests/integration/targets/ios_bgp_address_family/tests/cli/replaced.yaml
- tests/integration/targets/ios_bgp_address_family/vars/main.yaml
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.12.txt
- tests/sanity/ignore-2.9.txt
- tests/unit/modules/network/ios/fixtures/ios_bgp_address_family.cfg
- tests/unit/modules/network/ios/test_ios_bgp_address_family.py
To update ios_address_family route map and prefix_list param to accept list of params instead of dict. Fxes #267  and #333
ios_address_family
```paste below
```
> To update ios_address_family route map and prefix_list param to accept list

- changelogs/fragments/ios_user_issue.yaml
- plugins/modules/ios_user.py
Fixes #167 
ios_user
Key `password_type` does not exists if password was not set yet to this user. 
```paste below
```
> Fix setting password for new user Update ios_user.py

- changelogs/config.yaml
- changelogs/fragments/doc_broken_link.yaml
- docs/cisco.ios.ios_config_module.rst
- docs/cisco.ios.ios_interface_module.rst
- docs/cisco.ios.ios_logging_global_module.rst
- docs/cisco.ios.ios_prefix_lists_module.rst
- docs/cisco.ios.ios_route_maps_module.rst
- plugins/doc_fragments/fragments/docs_issue.yaml
- plugins/doc_fragments/ios.py
- plugins/modules/ios_config.py
- plugins/modules/ios_interface.py
- plugins/modules/ios_logging_global.py
- plugins/modules/ios_prefix_lists.py
- plugins/modules/ios_route_maps.py
> Doc fix for broken links

- changelogs/fragments/sample_commands_added_l3_interface.yaml
- docs/cisco.ios.ios_l3_interfaces_module.rst
- plugins/modules/ios_l3_interfaces.py
l3_interface doc sample commands added
l3_interfaces
```paste below
```
> l3_interface sample commands example added

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/291_add_vrf_support_ios_ntp.yaml
- changelogs/fragments/ios_l3_interfaces_module_rm_implimentation.yaml
- changelogs/fragments/ios_logging_command_template.yaml
- changelogs/fragments/ios_logging_doc_update_test_fix.yaml
- changelogs/fragments/ios_ntp_foc_update.yaml
- changelogs/fragments/provider_testing.yaml
- changelogs/fragments/sample_commands_added_l3_interface.yaml
Prep for IOS minor release 2.4.0
> Prep for Release 2.4.0

- changelogs/fragments/added_entry_galaxy.yaml
- galaxy.yml
added 'issues' to 'galaxy.yml' (replaces #406)
- galaxy.yml Pull Request
- galaxy.yml
> added 'issues' to 'galaxy.yml'

- changelogs/fragments/set_allow_duplicates.yaml
- tests/integration/targets/prepare_ios_tests/meta/main.yaml
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>
set allow_duplicates to true in prepare_ios_tests to support network-ee.
```paste below
```
> allow_duplicates for prepare_ios_tests

- changelogs/fragments/hostname_redirects.yaml
- meta/runtime.yml
Add redirects for ios_hostname
ios_hostname
> Add redirects for ios_hostname

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/492-snmp-fact-view-key-correction.yaml
- changelogs/fragments/acl_2_6.yaml
- changelogs/fragments/acls_bugfix_and_option_deprication.yaml
- changelogs/fragments/fix_fiveGigabit_name.yaml
- changelogs/fragments/fix_vlan.yaml
- changelogs/fragments/hostname_redirects.yaml
- changelogs/fragments/hostname_resource_module.yaml
- changelogs/fragments/snmp_server_feature_user.yaml
- changelogs/fragments/static_route_interface_issue.yaml
> Prep for release 2.7.0

- changelogs/fragments/fqcn_corrected_doc.yaml
- docs/cisco.ios.ios_banner_module.rst
- docs/cisco.ios.ios_command_module.rst
- docs/cisco.ios.ios_config_module.rst
- docs/cisco.ios.ios_facts_module.rst
- docs/cisco.ios.ios_interface_module.rst
- docs/cisco.ios.ios_l2_interface_module.rst
- docs/cisco.ios.ios_l3_interface_module.rst
- docs/cisco.ios.ios_linkagg_module.rst
- docs/cisco.ios.ios_lldp_module.rst
- docs/cisco.ios.ios_logging_module.rst
- docs/cisco.ios.ios_ntp_module.rst
- docs/cisco.ios.ios_ping_module.rst
- docs/cisco.ios.ios_static_route_module.rst
- docs/cisco.ios.ios_system_module.rst
- docs/cisco.ios.ios_user_module.rst
- docs/cisco.ios.ios_vlan_module.rst
- docs/cisco.ios.ios_vrf_module.rst
- plugins/doc_fragments/ios.py
corrects docs generation using collection_perp on older module docs.
> doc fix fqcn for older modules

- changelogs/fragments/fix_ip_ranges.yaml
- tests/integration/targets/ios_logging_global/tests/cli/_populate_config.yaml
- tests/integration/targets/ios_logging_global/tests/cli/merged.yaml
- tests/integration/targets/ios_logging_global/tests/cli/overridden.yaml
- tests/integration/targets/ios_logging_global/tests/cli/rendered.yaml
- tests/integration/targets/ios_logging_global/tests/cli/replaced.yaml
- tests/integration/targets/ios_logging_global/vars/main.yaml
- tests/integration/targets/ios_ntp_global/tests/cli/_parsed.cfg
- tests/integration/targets/ios_ntp_global/tests/cli/_populate_config.yaml
- tests/integration/targets/ios_ntp_global/tests/cli/overridden.yaml
- tests/integration/targets/ios_ntp_global/tests/cli/rendered.yaml
- tests/integration/targets/ios_ntp_global/vars/main.yaml
- tests/integration/targets/ios_snmp_server/tests/cli/_parsed.cfg
- tests/integration/targets/ios_snmp_server/tests/cli/_populate_config.yaml
- tests/integration/targets/ios_snmp_server/tests/cli/merged.yaml
- tests/integration/targets/ios_snmp_server/tests/cli/rendered.yaml
- tests/integration/targets/ios_snmp_server/vars/main.yaml
update integration tests with proper ip ranges
- Trivial change
> update integration tests with proper ip ranges

- changelogs/fragments/sanity_fix_docs.yaml
- docs/cisco.ios.ios_cliconf.rst
- plugins/cliconf/ios.py
> sanity fix

- changelogs/fragments/bgp_global_optimization copy.yaml
- plugins/module_utils/network/ios/facts/acl_interfaces/acl_interfaces.py
- plugins/module_utils/network/ios/facts/acls/acls.py
- plugins/module_utils/network/ios/facts/bgp_address_family/bgp_address_family.py
- plugins/module_utils/network/ios/facts/bgp_global/bgp_global.py
- plugins/module_utils/network/ios/facts/interfaces/interfaces.py
- plugins/module_utils/network/ios/facts/ospf_interfaces/ospf_interfaces.py
- plugins/module_utils/network/ios/facts/ospfv2/ospfv2.py
- plugins/module_utils/network/ios/facts/ospfv3/ospfv3.py
- plugins/module_utils/network/ios/facts/prefix_lists/prefix_lists.py
- plugins/module_utils/network/ios/facts/route_maps/route_maps.py
- plugins/module_utils/network/ios/facts/static_routes/static_routes.py
- tests/integration/targets/ios_static_routes/tests/cli/_add_extra_ipv6_data.yaml
- tests/integration/targets/ios_static_routes/tests/cli/_initial_setup_config.yaml
- tests/integration/targets/ios_static_routes/tests/cli/_remove_extra_ipv6_data.yaml
- tests/integration/targets/ios_static_routes/tests/cli/deleted.yaml
- tests/integration/targets/ios_static_routes/tests/cli/gathered.yaml
- tests/integration/targets/ios_static_routes/tests/cli/merged.yaml
- tests/integration/targets/ios_static_routes/tests/cli/overridden.yaml
- tests/integration/targets/ios_static_routes/tests/cli/rendered.yaml
- tests/integration/targets/ios_static_routes/tests/cli/replaced.yaml
- tests/unit/modules/network/ios/test_ios_static_routes.py
ios_static_routes to consider config only with routes
```paste below
```
> [ios_static_routes] to consider config only with routes

- changelogs/fragments/add_alias_to_logging_g_hosts.yml
- docs/cisco.ios.ios_logging_global_module.rst
- plugins/module_utils/network/ios/argspec/logging_global/logging_global.py
- plugins/module_utils/network/ios/config/logging_global/logging_global.py
- plugins/module_utils/network/ios/facts/logging_global/logging_global.py
- plugins/module_utils/network/ios/rm_templates/logging_global.py
- plugins/modules/ios_logging_global.py
- tests/integration/targets/ios_logging_global/tests/cli/overridden.yaml
- tests/integration/targets/ios_logging_global/tests/cli/replaced.yaml
- tests/integration/targets/ios_logging_global/vars/main.yaml
- tests/unit/modules/network/ios/test_ios_logging_global.py
adds an alias for hostname to be replaced with host 
```paste below
```
> [logging_global] adds alias for hostname to be replaced with host 

- changelogs/fragments/fix_fqcn_netcommon.yml
- tests/integration/targets/ios_smoke/tasks/cli.yaml
- tests/integration/targets/ios_smoke/tests/cli/caching.yaml
- tests/integration/targets/ios_smoke/tests/cli/misc_tests.yaml
Add fqcn to ansible_connection to support stable-2.9 
tests
```paste below
```
> Add fqcn to ansible_connection to support stable-2.9 

- changelogs/fragments/fix_sanity_issues.yaml
- plugins/modules/ios_vrf.py
Sanity fix ios_vrf doc
ios_vrf
```paste below
```
> [vrf] update sanity fix

- changelogs/fragments/logging_global_571.yaml
- plugins/module_utils/network/ios/rm_templates/logging_global.py
- tests/unit/modules/network/ios/test_ios_logging_global.py
fix parser for monitor and buffered config
logging_global
```paste below
```
> [logging_global] fix parser for monitor and buffered config

- changelogs/fragments/bgp_global_569.yaml
- plugins/module_utils/network/ios/rm_templates/bgp_global.py
- tests/unit/modules/network/ios/test_ios_bgp_global.py
fix command generation for local_as attribute
bgp_global
```paste below
```
> [bgp_global] fix command generation for local_as attribute

- changelogs/fragments/snmp_server_view_group_fix.yaml
- plugins/module_utils/network/ios/config/snmp_server/snmp_server.py
- tests/unit/modules/network/ios/test_ios_snmp_server.py
update command formation of views and groups
snmp_server
```paste below
```
> [snmp_server] update command formation of views and groups

- .github/workflows/test.yml
> GitHub actions run sanity and unit tests

- .github/workflows/test.yml
- changelogs/fragments/gha_update.yml
- pyproject.toml
- test-requirements.txt
> update GHA tests

- changelogs/fragments/add_redirects_action.yml
- meta/runtime.yml
> Add redirects

- changelogs/fragments/l2_vlan_tag.yaml
- plugins/module_utils/network/ios/facts/l2_interfaces/l2_interfaces.py
- tests/integration/targets/prepare_ios_tests/tasks/main.yml
fix vlan_tag attribute to match proper attribute options only
l2_interfaces
```paste below
```
> [l2_interfaces] fix vlan_tag attribute

- changelogs/fragments/snmp_envmon.yaml
- docs/cisco.ios.ios_snmp_server_module.rst
- plugins/module_utils/network/ios/argspec/snmp_server/snmp_server.py
- plugins/module_utils/network/ios/rm_templates/snmp_server.py
- plugins/modules/ios_snmp_server.py
- tests/sanity/ignore-2.14.txt
- tests/unit/modules/network/ios/test_ios_snmp_server.py
Add envmon traps feature with snmp_server
snmp_server
```paste below
```
> [snmp_server] Add envmon traps feature with snmp_server

- CHANGELOG.rst
changelog.yaml was updated, but CHANGELOG.rst was not regenerated from it.
> Regenerate changelog

- changelogs/fragments/fix_opState_facts.yaml
- plugins/module_utils/network/ios/facts/legacy/base.py
fix tailing white space on operation state
facts ios
```paste below
```
> [facts] fix tailing white space on operation state

- changelogs/fragments/acl_doc.yaml
- docs/cisco.ios.ios_acls_module.rst
- plugins/modules/ios_acls.py
fix attribute description in the documentation
ios_acls
```paste below
```
> [ios_acls] - fix attribute description in documentation

- changelogs/fragments/acl_fix_object_group.yaml
- plugins/module_utils/network/ios/config/acls/acls.py
- plugins/module_utils/network/ios/facts/acls/acls.py
- plugins/module_utils/network/ios/rm_templates/acls.py
- plugins/modules/ios_acls.py
- tests/integration/targets/ios_acls/tests/cli/rtt.yaml
- tests/integration/targets/ios_acls/vars/main.yaml
- tests/unit/modules/network/ios/test_ios_acls.py
ACL bug fixes and features
- _eq_ commands now are interpreted correctly for comparison.  `20 permit udp any any eq 23`  - > `20 permit udp any any eq telnet`
- for _replaced_ and _overridden_ state negate commands are fired before normal commands.
- added support for `object-group-service` under the protocol attribute
ios_acls
```paste below
```
> [acls] bug fixes and features

- changelogs/fragments/l2_interface_fix.yaml
- changelogs/fragments/l2_interface_fix_replaced_state.yaml
- plugins/module_utils/network/ios/config/l2_interfaces/l2_interfaces.py
- tests/unit/modules/network/ios/test_ios_l2_interfaces.py
fix replaced state on vlan removal
l2_interfaces
```paste below
```
> [l2_interfaces] fix replaced state on vlan removal

- changelogs/fragments/l3_interface_default_fix.yaml
- plugins/module_utils/network/ios/rm_templates/l3_interfaces.py
- tests/unit/modules/network/ios/test_ios_l3_interfaces.py
fix attributes generating values on attribute value being false.
l3_interfaces
```paste below
```
> [l3_interfaces] handle command generation on attribute value being false

- .pre-commit-config.yaml
- changelogs/fragments/reorder_parsers_bgp_add.yaml
- docs/cisco.ios.ios_bgp_module.rst
- docs/cisco.ios.ios_config_module.rst
- docs/cisco.ios.ios_linkagg_module.rst
- docs/cisco.ios.ios_logging_module.rst
- plugins/module_utils/network/ios/config/bgp_address_family/bgp_address_family.py
- plugins/module_utils/network/ios/rm_templates/bgp_address_family.py
- plugins/modules/ios_bgp.py
- plugins/modules/ios_config.py
- plugins/modules/ios_linkagg.py
- plugins/modules/ios_logging.py
- tests/integration/targets/ios_bgp_address_family/tests/cli/_initial_vrf_setup.yaml
- tests/integration/targets/ios_bgp_address_family/tests/cli/deleted.yaml
- tests/integration/targets/ios_bgp_address_family/tests/cli/overridden.yaml
- tests/integration/targets/ios_bgp_address_family/vars/main.yaml
parsers re-ordering to generate commands in correct orders
bgp_address_family
```paste below
```
> [bgp_address_family] reorder parsers based on peer_group

- changelogs/fragments/retry_ios_command.yaml
- docs/cisco.ios.ios_command_module.rst
- plugins/modules/ios_command.py
- tests/unit/modules/network/ios/test_ios_command.py
ref https://github.com/ansible-collections/cisco.nxos/pull/621
ios_command
> [command] run at least once when retries is 0 

- changelogs/fragments/fix_uts.yaml
- plugins/module_utils/network/ios/facts/acls/acls.py
- plugins/module_utils/network/ios/facts/ospfv2/ospfv2.py
- plugins/module_utils/network/ios/facts/ospfv3/ospfv3.py
- plugins/module_utils/network/ios/utils/utils.py
Test fix
- Testfix Pull Request
```paste below
```
> Fix references, on netcommon changes

- changelogs/fragments/acls_object_group_fix.yaml
- changelogs/fragments/bgp_shutdown.yaml
- changelogs/fragments/ospfv2_module_docfix.yml
- plugins/module_utils/network/ios/facts/acls/acls.py
- plugins/module_utils/network/ios/rm_templates/acls.py
- tests/unit/modules/network/ios/test_ios_acls.py
fix object-groups facts rendering
```paste below
```
> [acl] fix object-groups facts rendering

- plugins/module_utils/network/ios/rm_templates/acls.py
- tests/unit/modules/network/ios/test_ios_acls.py
fix acls sequence regex
ios_acls
```paste below
```
> fix acls sequence regex

- changelogs/fragments/fix_host_acls_rendering.yaml
- plugins/module_utils/network/ios/rm_templates/acls.py
- tests/unit/modules/network/ios/test_ios_acls.py
fix parsers to parse host configuration correctly
ios_acls
```paste below
```
> [ios_acls] - fix host rendering

- changelogs/fragments/vrf_lite_ospf_v2_v3.yml
- galaxy.yml
- plugins/module_utils/network/ios/rm_templates/ospfv2.py
- plugins/module_utils/network/ios/rm_templates/ospfv3.py
- tests/unit/modules/network/ios/test_ios_ospfv2.py
fix vrf_lite rendering config
ospfv2
ospfv3
```paste below
```
> opsfv2 and v3 - fix vrf_lite rendering

- changelogs/fragments/interfaces_staticorutes.yml
- docs/cisco.ios.ios_interfaces_module.rst
- docs/cisco.ios.ios_static_routes_module.rst
- plugins/modules/ios_interfaces.py
- plugins/modules/ios_static_routes.py
> Doc static routes and interfaces

- tests/integration/targets/ios_snmp_server/tests/cli/_populate_config.yaml
- tests/integration/targets/ios_snmp_server/tests/cli/_remove_config.yaml
PR for checking SNMP_SERVER integration test issue
- Tests fix
- `ios_snmp_server`
> snmp logs check pr

- changelogs/fragments/snmp_log.yml
- tests/integration/targets/ios_snmp_server/tests/cli/_populate_config.yaml
- tests/integration/targets/ios_snmp_server/tests/cli/_remove_config.yaml
Added Changes to integration test to show snmp v3 users
- Testing Issue Fix
> added snmp user integration test

- changelogs/fragments/facts_fix.yml
- plugins/module_utils/network/ios/facts/legacy/base.py
- tests/unit/modules/network/ios/fixtures/ios_facts_dir
- tests/unit/modules/network/ios/fixtures/ios_facts_show_processes_cpu
- tests/unit/modules/network/ios/test_ios_facts.py
correct reference to data for generating cpu_utilzation data and test fixes
- test fix full request
base.py
```paste below
```
> [ios_facts] correct reference to data and test fixes

- changelogs/fragments/enable_states.yml
- docs/cisco.ios.ios_bgp_global_module.rst
- docs/cisco.ios.ios_lacp_module.rst
- docs/cisco.ios.ios_lldp_global_module.rst
- docs/cisco.ios.ios_service_module.rst
- plugins/module_utils/network/ios/argspec/bgp_global/bgp_global.py
- plugins/module_utils/network/ios/argspec/lacp/lacp.py
- plugins/module_utils/network/ios/argspec/lldp_global/lldp_global.py
- plugins/module_utils/network/ios/argspec/service/service.py
- plugins/module_utils/network/ios/config/bgp_global/bgp_global.py
- plugins/module_utils/network/ios/config/lacp/lacp.py
- plugins/module_utils/network/ios/config/lldp_global/lldp_global.py
- plugins/module_utils/network/ios/config/service/service.py
- plugins/modules/ios_bgp_global.py
- plugins/modules/ios_lacp.py
- plugins/modules/ios_lldp_global.py
- plugins/modules/ios_service.py
- tests/unit/modules/network/ios/test_ios_bgp_global.py
- tests/unit/modules/network/ios/test_ios_lacp.py
- tests/unit/modules/network/ios/test_ios_lldp_global.py
- tests/unit/modules/network/ios/test_ios_service.py
Enable overridden state for all the modules where the overridden state was not present.
- Trivial
bgp_global
lldp_global
service
lacp
```paste below
```
> Support all action states for modules

- changelogs/fragments/update_ospf_docs.yaml
- docs/cisco.ios.ios_bgp_global_module.rst
- docs/cisco.ios.ios_ospf_interfaces_module.rst
- docs/cisco.ios.ios_ospfv2_module.rst
- docs/cisco.ios.ios_ospfv3_module.rst
- plugins/modules/ios_bgp_global.py
- plugins/modules/ios_ospf_interfaces.py
- plugins/modules/ios_ospfv2.py
- plugins/modules/ios_ospfv3.py
> Update OSPF examples(Health Check Documenation Activity)

- changelogs/fragments/fix_prefix_list_docs.yaml
- docs/cisco.ios.ios_prefix_lists_module.rst
- plugins/modules/ios_prefix_lists.py
> [Health check] Fix prefix_lists docs

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/acl_remaks_fresh.yml
- changelogs/fragments/error_parser_bug.yml
- changelogs/fragments/fix_config.yaml
- changelogs/fragments/ios_snmp_server_changes.yml
- galaxy.yml
This PR is for release for cisco ios version 5.3.0
> Release 5.2.0 prep

- changelogs/fragments/bgp_global_evpn_fix_2.yml
- plugins/module_utils/network/ios/facts/bgp_global/bgp_global.py
- plugins/module_utils/network/ios/rm_templates/bgp_global.py
Explicitly add a neighbor address to every parser
extension of this fix - https://github.com/ansible-collections/cisco.ios/pull/961
ios_bgp_global
```paste below
```
> ios_bgp_global - Explicitly add neighbor address to every parser

- changelogs/fragments/fix_ios_evpn_evi.yaml
- plugins/modules/ios_evpn_evi.py
- tests/integration/targets/ios_evpn_evi/tests/cli/_remove_config.yaml
Included codes to remove VLAN config to fix failing integration test.
ios_evpn_evi
```
> fixed failing integration test

- changelogs/fragments/fix_ios_vlan_config.yaml
- plugins/module_utils/network/ios/config/vlans/vlans.py
Fixed plugin generating empty VLAN definition.
ios_vlans
> Fixed empty VLAN definition.

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/fix_acls_old.yml
> 5.3.0 release prep

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/fix_ios_bgp_global_20231204173037.yaml
- changelogs/fragments/fix_ios_l3_interfacel_20231207172506.yaml
- changelogs/fragments/ios_facts_tests.yml
- changelogs/fragments/ios_l3_ipv6.yml
- changelogs/fragments/ios_user_fix.yml
- changelogs/fragments/ios_vlans_revert.yml
- changelogs/fragments/snmp_server_ipv6_acl.yml
- changelogs/fragments/template_revoke_bgp.yaml
- galaxy.yml
> Release 6.1.0

- changelogs/fragments/vlan_shutdown_fix.yaml
- plugins/module_utils/network/ios/config/vlans/vlans.py
- plugins/module_utils/network/ios/rm_templates/vlans.py
- tests/unit/modules/network/ios/test_ios_vlans.py
fix behaviour of shutdown attribute
- 
ios_vlans 
```paste below
```
> [ios_vlans] fix behaviour of shutdown attribute

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/module_defaults.yaml
- changelogs/fragments/vlan_shutdown_fix.yaml
- galaxy.yml
> Release 6.1.1

- tests/integration/targets/ios_user/tests/cli/basic.yaml
Fix ios_user integration test removing testing user, added it to the list of users not to purge
> Fix ios_user integration test removing testing user

- changelogs/fragments/bgp_global_shutdown.yml
- plugins/module_utils/network/ios/config/bgp_global/bgp_global.py
- plugins/module_utils/network/ios/rm_templates/bgp_global.py
- tests/integration/targets/ios_bgp_global/tests/cli/deleted.yaml
- tests/integration/targets/ios_bgp_global/tests/cli/merged.yaml
- tests/integration/targets/ios_bgp_global/vars/main.yaml
- tests/unit/modules/network/ios/test_ios_bgp_global.py
Fix shutdown attribute to negate on boolean false
ios_bgp_global
```paste below
```
> [bgp_global] Fix shutdown attribute to negate on boolean false

- changelogs/fragments/ios_acls_sticky.yml
- plugins/module_utils/network/ios/config/acls/acls.py
- plugins/modules/ios_acls.py
- tests/unit/modules/network/ios/test_ios_acls.py
Update acls action states with sticky remarks
ios_acls
```paste below
```
> [ios_acls] Update acls action states to support sticky behaviour of remarks

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/add_restore_support.yaml
- changelogs/fragments/sanityfix.yml
- galaxy.yml
> Prepare release 8.0.0

- changelogs/fragments/ios_logging.yml
- docs/cisco.ios.ios_logging_global_module.rst
- plugins/modules/ios_logging_global.py
- tests/integration/targets/ios_logging_global/tests/cli/merged.yaml
This PR fixes - #1072 
Update documentation - ios_logging_global for severity attribute within buffered.
> Added doc changes for logging_global

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1097-ios-facts-MiB.yml
- changelogs/fragments/1101-typo-ios_service.yml
- changelogs/fragments/pr-1095-fragment.yaml
- changelogs/fragments/vlan_err_reg.yaml
- galaxy.yml
> Release 9.0.1

- changelogs/fragments/pylint_fix.yaml
- plugins/module_utils/network/ios/rm_templates/ospfv2.py
Fix pylint variable potential unbound error
> Fixes pylint error

- changelogs/fragments/bgp_add_fam_max_path.yaml
- docs/cisco.ios.ios_bgp_address_family_module.rst
- plugins/module_utils/network/ios/argspec/bgp_address_family/bgp_address_family.py
- plugins/module_utils/network/ios/config/bgp_address_family/bgp_address_family.py
- plugins/module_utils/network/ios/rm_templates/bgp_address_family.py
- plugins/modules/ios_bgp_address_family.py
- tests/integration/targets/ios_bgp_address_family/tests/cli/merged.yaml
- tests/integration/targets/ios_bgp_address_family/tests/cli/rendered.yaml
- tests/integration/targets/ios_bgp_address_family/vars/main.yaml
- tests/unit/modules/network/ios/test_ios_bgp_address_family.py
Add support for maximum-path and maximum-secondary-path for `ios_bgp_address_family`
```paste below
ios8k#show running-config | section bgp
router bgp 65000
bgp log-neighbor-changes
bgp nopeerup-delay post-boot 10
bgp graceful-shutdown all neighbors 50 local-preference 100 community 100
neighbor 192.168.81.22 remote-as 65100
neighbor 192.168.81.38 remote-as 65101
!
address-family ipv4
bgp advertise-best-external
network 192.168.81.16 mask 255.255.255.248
network 192.168.81.32 mask 255.255.255.248
network 192.168.84.0
network 192.168.85.0
network 192.168.86.0
neighbor 192.168.81.22 activate
neighbor 192.168.81.22 default-originate
neighbor 192.168.81.22 soft-reconfiguration inbound
neighbor 192.168.81.38 activate
neighbor 192.168.81.38 default-originate
neighbor …
```
> [bgp_af] Add support for maximum-path and maximum-secondary-path

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/0-readme.yml
- changelogs/fragments/bgp_add_fam_max_path.yaml
- changelogs/fragments/fix-snmp-server-idempotency.yml
- changelogs/fragments/fix_interface_fifty_interface.yml
- changelogs/fragments/ios_static_routes.yaml
- changelogs/fragments/pylint_fix.yaml
- galaxy.yml
> Release 9.0.2

- README.md
- changelogs/fragments/support_section.yml
This PR adds the support section
Removed the Roadmap section
> Updated the Readme

- docs/cisco.ios.ios_vrf_interfaces_module.rst
- Add documentation for ios_vrf_interfaces since it was missed in the original PR.
ios_vrf_interfaces.py
> Add ios_vrf_interfaces documentation

- changelogs/fragments/fix_acls_tests.yaml
- plugins/module_utils/network/ios/config/route_maps/route_maps.py
- tests/integration/targets/ios_facts/tests/cli/all_facts.yaml
- tests/integration/targets/ios_vrf_interfaces/tests/common/_populate_config.yaml
- tests/integration/targets/ios_vrf_interfaces/tests/common/_remove_config.yaml
- tests/integration/targets/ios_vrf_interfaces/tests/common/merged.yaml
- tests/integration/targets/ios_vrf_interfaces/tests/common/rtt.yaml
- tests/integration/targets/ios_vrf_interfaces/vars/main.yaml
Fixes facts,vrf_interfaces tests and fixes logic for route maps acls
- Test Fix
The above changes fixes facts and vrf_interfaces test cases, it also fixes the logic for acls in route_maps which was modified in this pr - https://github.com/ansible-collections/cisco.ios/pull/1138/files?diff=split&w=0
The above has been tested against cml
> Fixes facts,vrf_interfaces and fixes logic for route maps acls

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/add_vrf_address_family.yaml
- changelogs/fragments/ana_602_fix_vlan_context_gathering.yaml
- changelogs/fragments/fix_acls_tests.yaml
- changelogs/fragments/fix_facts_gather.yaml
- changelogs/fragments/fix_purge_and_overridden_operations.yaml
- changelogs/fragments/rm_vrf_interfaces.yaml
- changelogs/fragments/route_maps_acl_fix.yaml
- galaxy.yml
> Release PREP 9.1.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/fix_acls_remark.yaml
- changelogs/fragments/fix_ci_upstream.yaml
- galaxy.yml
> Release 9.1.2

- README.md
- changelogs/fragments/bump216.yml
- meta/runtime.yml
- tests/config.yml
- tests/integration/targets/ios_vlans/tasks/main.yaml
Update minimum ansible required version 2.16
> Update minimum ansible required version 2.16

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/all_intefaces.yaml
- changelogs/fragments/bump216.yml
- galaxy.yml
> Release PR 10.0.0

- tests/unit/modules/network/ios/test_ios_logging_global.py
- tests/unit/modules/utils.py
https://issues.redhat.com/browse/AAP-41594
https://github.com/ansible/ansible/pull/84621
> Fix tests for the data-tagging PR

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1198-fix-docs-hsrp_interfaces.yml
> Release PR
