ansible-collections/cisco.ios

plugins/module_utils/network/ios/config/l3_interfaces/l3_interfaces.py
tests/integration/targets/ios_l3_interfaces/tests/cli/_remove_config.yaml
tests/integration/targets/ios_l3_interfaces/tests/cli/merged.yaml
tests/integration/targets/ios_l3_interfaces/vars/main.yaml

To fix the issue where loopback address wasn't populated as expected via ios_l3_interfaces module, fixes issue raised via #43
ios_l3_interfaces
```paste below
```

To fix the issue where loopback address wasn't populated as expected via ios_l3_interfaces module

---

plugins/module_utils/network/ios/config/vlans/vlans.py
tests/integration/targets/ios_vlans/tests/cli/replaced.yaml
tests/integration/targets/ios_vlans/vars/main.yaml

Fix ios_vlans replace operation with non-existing VLAN config as with non-existing VLANs replace operation was skipping and showing changed as False which was ideally incorrect. Vlans config should be fired even if the VLANs don’t pre-exist with replace operation as well. Both merge and override operation is behaving as expected.
ios_vlans
```paste below
```

Fix ios_vlans replace operation with non-existing vlan config

---

plugins/module_utils/network/ios/facts/l2_interfaces/l2_interfaces.py

Resolves issue where L2 interfaces were parsing facts incorrectly, resolves issue #58 
ios_l2_interfaces
```paste below
```

Resolves issue where L2 interfaces were parsing facts incorrectly

---

tests/integration/targets/ios_command/tests/cli/error_regex.yaml
tests/integration/targets/ios_user/tasks/cli.yaml
tests/integration/targets/ios_user/tests/cli/auth.yaml

*  Increase logging buffer size on device
before issuing logs that matches error regex
* increase shell timeout to avoid ios_user failure
```paste below
```

Fix ios_command regex failure and ios_user shell timeout issue

---

plugins/module_utils/network/ios/facts/vlans/vlans.py

Resolves traceback error in ios_vlans resource module where user was facing list index out of range error.  #63 
ios_vlans
```paste below
```

Resolves traceback error in ios_vlans resource module

---

plugins/module_utils/network/ios/config/interfaces/interfaces.py
plugins/module_utils/network/ios/config/l2_interfaces/l2_interfaces.py
plugins/module_utils/network/ios/config/lacp_interfaces/lacp_interfaces.py
plugins/module_utils/network/ios/config/lag_interfaces/lag_interfaces.py
plugins/module_utils/network/ios/config/lldp_interfaces/lldp_interfaces.py

Fixes Interface normalizing for all of interfaces resource module. Fixes #73 
ios_interfaces.py
ios_l2_interfaces.py
ios_lldp_interfaces.py
ios_lag_interfaces.py
ios_lacp_interfaces.py
```paste below
```

Fixes Interface normalizing for all of interfaces resource module

---

plugins/module_utils/network/ios/config/acls/acls.py
plugins/modules/ios_acls.py
tests/integration/targets/ios_acls/tests/cli/merged.yaml
tests/integration/targets/ios_acls/vars/main.yaml

To fix IOS ACLs merge state, and now users can give input only to value that they want to update using merge state and module will tc of merging the have and want dict. Resolves bug raised in #20 
ios_acls
```paste below
```

To fix IOS ACLs merge state

---

plugins/module_utils/network/ios/config/acls/acls.py

Depends-On: https://github.com/ansible-collections/cisco.ios/pull/86
To fix IOS resource module traceback error, which was failing as `po_val` not getting populated when protocol_options other than `icmp`, `igmp` and `tcp` was set. PR fixes #13
ios_acls
```paste below
```

To fix IOS resource module traceback error 

---

plugins/module_utils/network/ios/facts/legacy/base.py

Update regex to look for ' IOS-XE ' in show version output. Previous regex was unable to match older IOS-XE versions (Version 03.04.02.SG on cat4500 for example).
Closes #71
ios_facts
IOS-XE does not appear in any IOS show version outputs I have tested. Set the regex to '\sIOS-XE\s' as whitespace characters should not be allowed in hostname in case someone is weird and does that.
Previous regex does not match:
``` 
Cisco IOS Software, IOS-XE Software, Catalyst 4500 L3 Switch Software (cat4500e-UNIVERSALK9-M), Version 03.04.02.SG RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2013 by Cisco Systems, Inc.
Compiled Thu 05-Sep-13 19:06 by prod_rel_team
Cisco IOS-XE software, Copyright (c) 2005-2010, 2012 by cisco Systems, …
```

update regex match string for parse_iostype

---

changelogs/fragments/124_resolved_ios_acls_issue.yaml
plugins/module_utils/network/ios/config/acls/acls.py
plugins/module_utils/network/ios/facts/acls/acls.py
tests/unit/modules/network/ios/test_ios_acls.py

To fix the issue where IOS ACLs was complaining in absence of protocol option value, PR fixes the issue raised in #122
ios_acls
```paste below
```

To fix the issue where ios acls was complaining in absence of protocol option value

---

changelogs/fragments/132_update_ios_l3_doc_issue.yaml
plugins/modules/ios_l3_interfaces.py

To fix the incorrect command displayed under ios_l3_interfaces resource module docs. Closes issue: #132 
ios_l3_interfaces
```paste below
```

To fix the incorrect command displayed under ios_l3_interfaces resource module docs

---

changelogs/fragments/144_add_interface_tunnel_issue.yml
plugins/module_utils/network/ios/utils/utils.py

Fixes: https://github.com/ansible-collections/cisco.ios/issues/144
```paste below
```

Added support for interface Tunnel

---

changelogs/fragments/146_add_cdp_platform_info_to_ios_facts.yaml
plugins/module_utils/network/ios/facts/legacy/base.py
tests/unit/modules/network/ios/test_ios_facts.py

Add cdp platform information to ios_facts ansible_net_neighbors return value.
- ios_facts
Before change (partial output)
```
"GigabitEthernet1/0/17": [
{
"host": "cisco.ap.local",
"port": "GigabitEthernet0"
}
],
```
After change (partial output)
```
"GigabitEthernet1/0/17": [
{
"host": "cisco.ap.local",
"platform": "cisco AIR-CAP702W-E-K9",
"port": "GigabitEthernet0"
}
],
```

Add cdp platform information to ios_facts output

---

changelogs/fragments/135_accept_list_of_dict_for_ospfv2_network.yaml
plugins/module_utils/network/ios/argspec/ospfv2/ospfv2.py
plugins/module_utils/network/ios/rm_templates/ospfv2.py
plugins/modules/ios_ospfv2.py
tests/integration/targets/ios_ospfv2/tests/cli/_populate_config.yaml
tests/integration/targets/ios_ospfv2/tests/cli/merged.yaml
tests/integration/targets/ios_ospfv2/tests/cli/rendered.yaml
tests/integration/targets/ios_ospfv2/tests/cli/rtt.yaml
tests/integration/targets/ios_ospfv2/vars/main.yaml
tests/unit/modules/network/ios/test_ios_ospfv2.py

Allowing ios_ospfv2 to accept multiple networks per process, so changing the logic of accepting list of dict instead of single dict. PR fixes issue: #135
ios_ospfv2
```paste below
```

Allowing ios_ospfv2 to accept multiple networks per process

---

changelogs/fragments/175_fix_ios_vlans_when_name_had_remote.yaml
plugins/module_utils/network/ios/facts/vlans/vlans.py
tests/unit/modules/network/ios/fixtures/ios_vlans_config.cfg
tests/unit/modules/network/ios/test_ios_vlans.py

To fix ios_vlans traceback bug when the name had Remote in it and added unit TC for the module. Fixes #175 
ios_vlans
```paste below
```

To fix ios_vlans traceback bug when the name had Remote in it and added unit TC for the module

---

changelogs/fragments/137_ios_static_routes_idempotency_issue.yaml
plugins/module_utils/network/ios/utils/utils.py
tests/unit/modules/network/ios/fixtures/ios_static_routes_config.cfg
tests/unit/modules/network/ios/test_ios_static_routes.py

To fix IOS static routes idempotency issue coz of netmask to cidr conversion. Fixes #137 and #178 
```paste below
```

To fix IOS static routes idempotency issue coz of netmask to cidr conversion

---

changelogs/fragments/63_support_for_very_long_vlan_name.yaml
plugins/module_utils/network/ios/facts/vlans/vlans.py
tests/unit/modules/network/ios/fixtures/ios_vlans_config.cfg
tests/unit/modules/network/ios/test_ios_vlans.py

To fix the traceback issue for longer vlan name having more than 32 characters. Fixes issue raised in #63 
ios_vlans
```paste below
```

To fix the traceback issue for longer vlan name having more than 32 characters

---

changelogs/fragments/161_static_route_facts_cmd_update.yaml
plugins/module_utils/network/ios/facts/static_routes/static_routes.py

To fix ios_static_routes where interface ip route-cache config was being parsed and resulted trackback. Fixes issue: #161 
```paste below
```

To fix ios_static_routes where interface ip route-cache config was being parsed and resulted traceback

---

requirements.txt

This allows us to start supporting libssh.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/678
Depends-On: https://github.com/ansible-collections/ansible.netcommon/pull/169

Add ansible-pylibssh dependency

---

changelogs/fragments/216_fix_command_rejected_issue.yml
plugins/terminal/ios.py
tests/integration/targets/ios_config/tests/cli/defaults.yaml

Hi all, allow check "Command Reject" on config mode.
Resolves: #216 
In the current implementation, configuring with "ios_config" not check if command is rejected and ansible still reports "changed", comes back and reports success, and ignores the fact they were rejected.
```
SWITCH#sh run int gigabitEthernet 1/3
Building configuration...
Current configuration : 378 bytes
!
interface GigabitEthernet1/3
switchport trunk encapsulation dot1q
switchport trunk native vlan 4094
switchport mode trunk
mtu 9198
load-interval 30
media-type rj45
negotiation auto
no keepalive
no lldp transmit
no lldp receive
no cdp enable
spanning-tree portfast network
spanning-tree bpdufilter enable
end
- name: "COMMAND"
ios_config:
lines:
- switchport private-vlan mapping 10 6000
parents: …
```

IOS_CONFIG - incorrectly claims success when 'Command Rejected'

---

changelogs/fragments/217_added_support_for_new_ios_interfaces.yml
plugins/module_utils/network/ios/ios.py
plugins/module_utils/network/ios/utils/utils.py
tests/unit/modules/network/ios/fixtures/ios_l2_interfaces.cfg
tests/unit/modules/network/ios/test_ios_l2_interfaces.py

To add support for `TwoGigabitEthernet` interface option from an IOS standpoint. Fixes #217 
ios_*_interfaces
```paste below
```

To add support for TwoGigabitEthernet interface option from IOS standpoint

---

changelogs/fragments/257_ios_acls_throwing_nonetype.yml
plugins/module_utils/network/ios/config/acls/acls.py
plugins/module_utils/network/ios/facts/acls/acls.py
tests/unit/modules/network/ios/fixtures/ios_acls_config.cfg
tests/unit/modules/network/ios/test_ios_acls.py

To fix ios_acls Nonetype error when aces are empty. Fixes #257
ios_acls
```paste below
```

To fix ios_acls Nonetype error when aces are empty

---

changelogs/fragments/245_fix_ios_l2_interface_list_range_issue.yaml
plugins/module_utils/network/ios/config/l2_interfaces/l2_interfaces.py
tests/unit/modules/network/ios/fixtures/ios_l2_interfaces.cfg
tests/unit/modules/network/ios/test_ios_l2_interfaces.py

PR to fix ios_l2_interfaces issue where it wasn’t working with range of vlans as expected. Fixes #245 
ios_l2_interfaces
```paste below
```

PR to fix ios_l2_interfaces issue where it wasn’t working with range of vlans as expected

---

changelogs/fragments/238_fix_acls_acl_name_traceback_error.yaml
plugins/module_utils/network/ios/rm_templates/acls.py

To fix ios_acls resource module acl_name traceback over some switches. Fixes #238 
ios_acls
```paste below
```

To fix ios_acls resource module acl_name traceback over some switches

---

changelogs/fragments/268_ios_vlans_traceback_fix.yml
plugins/module_utils/network/ios/facts/vlans/vlans.py
tests/unit/modules/network/ios/fixtures/ios_vlans_config.cfg

To fix ios_vlans traceback error when the empty line with just Ports information is available in the config. Fixes #268 
ios_vlans
```paste below
```

To fix ios_vlans traceback error when empty line with just Ports information is available in config

---

changelogs/fragments/319_fix_ios_bgp_af_next_hop_self_param.yaml
plugins/module_utils/network/ios/argspec/bgp_address_family/bgp_address_family.py
plugins/module_utils/network/ios/facts/bgp_address_family/bgp_address_family.py
plugins/modules/ios_bgp_address_family.py
tests/unit/modules/network/ios/fixtures/ios_bgp_address_family.cfg
tests/unit/modules/network/ios/test_ios_bgp_address_family.py

To fix ios_bgp_address_family neighbor next_hop_self param. Fixes #319 
ios_bgp_address_family
```paste below
```

To fix ios_bgp_address_family neighbor next_hop_self param

---

changelogs/fragments/18_325_ios_vlans_traceback_replace_override_fix.yaml
plugins/module_utils/network/ios/config/vlans/vlans.py
plugins/module_utils/network/ios/facts/vlans/vlans.py
plugins/modules/ios_vlans.py
tests/unit/modules/network/ios/test_ios_vlans.py

To fix ios_vlans replace and overridden inconsistent behaviour and traceback error. Fixes #18 and #325 
ios_vlans
```paste below
```

To fix ios_vlans replace and overridden inconsistent behaviour and traceback error

---

changelogs/fragments/207-fix-v12-logging-cmds.yaml
plugins/modules/ios_logging.py

Fixes #207 
Checks the start of the os_version string for v12 version instead of anywhere in the string. Otherwise it will match versions like 16.12.4.
ios_logging

Fix logging commands for v12 versions

---

changelogs/fragments/banner_issue_fix.yaml
docs/cisco.ios.ios_banner_module.rst
plugins/modules/ios_banner.py
tests/integration/targets/ios_banner/tests/cli/basic-login.yaml
tests/integration/targets/ios_banner/tests/cli/basic-motd.yaml
tests/integration/targets/ios_banner/tests/cli/basic-no-login.yaml
tests/integration/targets/ios_banner/tests/cli/multiple-login-exec.yaml
tests/unit/modules/network/ios/test_ios_banner.py

fixes-
#206 #156 #50
desc-
- Banner module not idempotent
- Fails when while space in the beginning/ back text
- The banner issue with ASCII art
- Introduction of new attribute for delimiter
ios_banner

Banner fix and modification

---

changelogs/fragments/317-authorize.yaml
tests/integration/targets/prepare_ios_tests/tasks/main.yml

`authorize` was removed from `ios_config` a while ago, but is still in the setup tasks when `show version` contains "IOS-XE" 
- Tests Pull Request
prepare_ios_tests

I guess we aren't testing XE right now?

---

changelogs/fragments/add-autoconfig-dhcp-to-l3_interfaces.yaml
plugins/module_utils/network/ios/config/l3_interfaces/l3_interfaces.py
plugins/module_utils/network/ios/facts/l3_interfaces/l3_interfaces.py
plugins/modules/ios_l3_interfaces.py
tests/integration/targets/ios_l3_interfaces/tests/cli/_parsed.cfg
tests/integration/targets/ios_l3_interfaces/tests/cli/_populate_config.yaml
tests/integration/targets/ios_l3_interfaces/tests/cli/merged.yaml
tests/integration/targets/ios_l3_interfaces/tests/cli/rendered.yaml
tests/integration/targets/ios_l3_interfaces/vars/main.yaml

Add support for autoconfig and dhcp keywords for IPv6 addresses in l3_interfaces.
l3_interfaces
Tested with IOS 15.2(2a)E1. Resubmit of #15

Add support for autoconfig and dhcp keywords for IPv6 addresses in l3_interfaces

---

changelogs/fragments/config_module_warning_msg.yaml
plugins/modules/ios_config.py

*  Currently the warning message for diff is thrown
for every module run.
*  Based on discussion here https://github.com/ansible/network/discussions/48
a better way of logging the message is through verbose
logs but verbose logging has a known issue https://github.com/ansible-collections/ansible.netcommon/issues/224
*  Hence moving the message under `warnings` key within the task
response if `changed=True`
ios_config
```paste below
```

Move warning message for ios_config module

---

changelogs/fragments/313_reordering_interface.yaml
plugins/module_utils/network/ios/ios.py
plugins/module_utils/network/ios/utils/utils.py

Fixes a bug/regression introduced by PR 262 where the TwoGigabit(tw) interface was matching and the TwentyFive(twe) was never matched.
ios_config
ansible.module_utils.connection.ConnectionError: interface TwoGigabitEthernet1/0/1\r
interface TwoGigabitEthernet1/0/1\r
^\r
% Invalid input detected at '^' marker.\r
\r
SWITCH-(config)#
failed: [SWITCH] (item={'name': 'TwentyFiveGigE1/0/1', 'description': 'PORT E1/23', 'ipv4': 'NA', 'enabled': 'TRUE', 'mtu': '1500', 'trusted': 'TRUE',
'no_switchport': 'FALSE'}) => {
"ansible_loop_var": "item",
"changed": false,
"item": {
"description": "PORT E1/23",
"enabled": "TRUE",
"ipv4": "NA",
"mtu": "1500",
"name": "TwentyFiveGigE1/0/1",
"no_switchport": "FALSE",
"trusted": "TRUE"
},
```paste below
```

Fix TwentyFive Gig matching

---

changelogs/fragments/345_update_prefix_list_and_acls_merge_behaviour.yaml
plugins/module_utils/network/ios/argspec/prefix_lists/prefix_lists.py
plugins/module_utils/network/ios/config/acls/acls.py
plugins/module_utils/network/ios/config/prefix_lists/prefix_lists.py
plugins/module_utils/network/ios/facts/prefix_lists/prefix_lists.py
plugins/module_utils/network/ios/rm_templates/prefix_lists.py
plugins/modules/ios_acls.py
plugins/modules/ios_prefix_lists.py
tests/integration/targets/ios_acls/tests/cli/merged.yaml
tests/integration/targets/ios_acls/vars/main.yaml
tests/integration/targets/ios_prefix_lists/tests/cli/_populate_config.yaml
tests/integration/targets/ios_prefix_lists/tests/cli/deleted.yaml
tests/integration/targets/ios_prefix_lists/tests/cli/merged.yaml
tests/integration/targets/ios_prefix_lists/tests/cli/overridden.yaml
tests/integration/targets/ios_prefix_lists/tests/cli/rendered.yaml
tests/integration/targets/ios_prefix_lists/tests/cli/replaced.yaml
tests/integration/targets/ios_prefix_lists/vars/main.yaml
tests/unit/modules/network/ios/test_ios_prefix_lists.py

To fix IOS ACLs and Prefix Lists RM to not negate config when using merge state, also fixes the Prefix-list model to accept `description` at the same level as `name`. Fixes #345 
ios_acls, ios_prefix_lists
```paste below
```

To fix IOS ACLs and Prefix Lists RM to not negate config when using merge state

---

changelogs/fragments/ios_acl_interfaces_doc_fix.yaml
docs/cisco.ios.ios_acl_interfaces_module.rst
plugins/modules/ios_acl_interfaces.py

fix doc ios_acl_interfaces example.
In `state: merged`, `ip access-group 123 out` should not be executed for `GigabitEthernet0/2`.
Because it is already set at Before State.
- `ios_acl_interfaces`

fix doc ios_acl_interfaces

---

changelogs/fragments/ios_user_test_fix.yaml
tests/integration/targets/ios_user/tests/cli/auth.yaml

Depends-on: https://github.com/ansible-collections/ansible.netcommon/pull/271
ios devices have trouble recovering when paramiko fails to authenticate with a private key.
As we are connecting with password only on these tests, clear the private_key_file var for these tests
- Test Pull Request
ios_user

Fixes ios_user tests when options are directly set

---

changelogs/fragments/199_become_not_working.yaml
plugins/terminal/ios.py

fix become,  when user privilege < 15 on use of become - privilege should be 15
extra checks added as the prompt checks for `#` that is common for all privilege level.
terminal/ios.py
user privilege
```paste below
an-iosl2-02#show privilege 
Current privilege level is 5
```
before -
```
tasks:
- ios_command:
commands: show privilege
register: privilege
become: yes
```
result - 
```
"stdout_lines": [
[
"Current privilege level is 5"
]
```
now-
```
"stdout_lines": [
[
"Current privilege level is 15"
]
```

fix become for privilege level < 15

---

changelogs/fragments/facts_vlan_issue.yaml
docs/cisco.ios.ios_facts_module.rst
docs/cisco.ios.ios_vlans_module.rst
plugins/cliconf/ios.py
plugins/module_utils/network/ios/facts/vlans/vlans.py
plugins/modules/ios_facts.py
plugins/modules/ios_vlans.py
tests/unit/modules/network/ios/test_ios_vlans.py
tests/unit/plugins/cliconf/test_ios.py

Fixes #356 
ios_facts:
won't break for l2 or l3 devices rather have VLAN resource module facts data empty for devices other than l2
ios_vlans:
for a playbook run other than the `rendered`/`parsed` state, the playbook is supposed to fail with an exception.
#TODO fix vlan unit tests
ios_fact
ios_vlans
```paste below
---
- name: Test VLANs
hosts: router
gather_facts: no
tasks:
- name: gather IOS facts for l3 device
cisco.ios.facts:
gather_subset: config
gather_network_resources:
- vlans
```
the above play won't get an exception while run against l3 device ^

Facts issue fix - Vlan to break for l3 devices

---

changelogs/fragments/bgp_add_fam_issue.yaml
docs/cisco.ios.ios_bgp_address_family_module.rst
plugins/module_utils/network/ios/argspec/bgp_address_family/bgp_address_family.py
plugins/module_utils/network/ios/config/bgp_address_family/bgp_address_family.py
plugins/module_utils/network/ios/facts/bgp_address_family/bgp_address_family.py
plugins/module_utils/network/ios/facts/facts.py
plugins/module_utils/network/ios/rm_templates/bgp_address_family.py
plugins/modules/ios_bgp_address_family.py
tests/integration/targets/ios_bgp_address_family/tests/cli/_parsed.cfg
tests/integration/targets/ios_bgp_address_family/tests/cli/parsed.yaml
tests/integration/targets/ios_bgp_address_family/vars/main.yaml
tests/unit/modules/network/ios/test_ios_bgp_address_family.py

closing #422 #392 
- fix BGP address family to support multiple neighbors
- Inconsistent naming of class in the module fixed as per cli_rm_builders rule
bgp_address_family

fix bgp address family to support multiple neighbours

---

changelogs/fragments/sd_wan_support.yaml
plugins/terminal/ios.py

devices in the sd-wan mode were unable to handle the `"terminal length 0"` command
Closing #349
/ios/plugins/terminal/ios.py
```json
fatal: [10.10.20.90]: FAILED! => {
"changed": false,
"invocation": {
"module_args": {
"commands": [
"request execute mkdir backups"
],
"interval": 1,
"match": "all",
"provider": null,
"retries": 10,
"wait_for": null
}
},
"msg": "unable to set terminal parameters"
}
```
fixed as - 
```json
ok: [10.10.20.90] => {
"changed": false,
"invocation": {
"module_args": {
"commands": [
"request execute mkdir backups"
],
"interval": 1,
"match": "all",
"provider": null,
"retries": 10,
"wait_for": null
}
},
"stdout": [
""
],
"stdout_lines": [
[
""
]
]
}
```
```json
ok: [10.10.20.90] => {
"changed": false,
"invocation": {
"module_args": {
"commands": …
```

Support to sd-wan terminal init commands

---

changelogs/fragments/sanity-213.yaml
tests/sanity/ignore-2.13.txt

Depends-on: https://github.com/ansible/ansible-zuul-jobs/pull/1143
https://github.com/ansible-collections/cisco.ios/pull/432 identified this issue, but as that PR is not meant to be merged, this will actually fix the failures
- Test Pull Request
```paste below
2021-10-01 14:01:07.484756 | centos-8-stream | Running sanity test "ignores"
2021-10-01 14:01:07.484837 | centos-8-stream | ERROR: Found 20 ignores issue(s) which need to be resolved:
2021-10-01 14:01:07.484961 | centos-8-stream | ERROR: tests/sanity/ignore-2.13.txt:2:66: Sanity test 'compile-2.6' does not exist
2021-10-01 14:01:07.484985 | centos-8-stream | ERROR: tests/sanity/ignore-2.13.txt:3:82: Sanity test 'compile-2.6' does not exist
2021-10-01 14:01:07.484993 | centos-8-stream | ERROR: tests/sanity/ignore-2.13.txt:4:76: …
```

2.13 sanity fixes

---

changelogs/fragments/fix_fiveGigabit_name.yaml
plugins/module_utils/network/ios/facts/l2_interfaces/l2_interfaces.py
plugins/module_utils/network/ios/ios.py
plugins/module_utils/network/ios/utils/utils.py
plugins/modules/ios_l2_interface.py
tests/unit/modules/network/ios/test_ios_l2_interfaces.py

Allows ios_facts to collect l2_interface information for FiveGigabitEthernet interfaces on Cisco Catalyst 9300 mGig switches.
Fixes #442
ios_facts
Before change: 
```json
{
"ansible_facts": {
"ansible_network_resources": {
"l2_interfaces": [
{
"name": "GigabitEthernet0/0"
},
{
"name": "GigabitEthernet1/1/1"
},
{
"name": "GigabitEthernet1/1/2"
},
{
"name": "GigabitEthernet1/1/3"
},
{
"name": "GigabitEthernet1/1/4"
}
]
}
}
}
```
After change:
```json
{
"ansible_facts": {
"ansible_network_resources": {
"l2_interfaces": [
{
"name": "GigabitEthernet0/0"
},
{
"name": "GigabitEthernet1/1/1"
},
{
"name": "GigabitEthernet1/1/2"
},
{
"name": "GigabitEthernet1/1/3"
},
{
"name": "GigabitEthernet1/1/4"
},
{
"name": "FiveGigabitEthernet1/0/1"
},
{
"name": …
```

Five gigabit ethernet

---

changelogs/fragments/static_route_interface_issue.yaml
plugins/module_utils/network/ios/config/static_routes/static_routes.py
plugins/module_utils/network/ios/facts/static_routes/static_routes.py
tests/unit/modules/network/ios/fixtures/ios_static_routes_config.cfg
tests/unit/modules/network/ios/test_ios_static_routes.py

static_routes was unable to determine the interface names with it was supplied within the destination
```paste below
```

static_routes unable to render Interfaces in facts properly

---

changelogs/fragments/fix_vlan.yaml
plugins/module_utils/network/ios/facts/vlans/vlans.py
tests/unit/modules/network/ios/test_ios_vlans.py

fix vlan not parsing names with space correctly 
fix vlan parsing range options correctly
Depends-On: https://github.com/ansible-collections/cisco.ios/pull/485
ios_vlan
```paste below
```

vlan bugfix | parsing range | parsing space in name |

---

changelogs/fragments/acl_2_6.yaml
plugins/module_utils/network/ios/facts/acls/acls.py
plugins/module_utils/network/ios/rm_templates/acls.py
tests/unit/modules/network/ios/test_ios_acls.py

IOS parsing standard ACLs wrongly, when matches are visible in running config
ios_acls
```paste below
```

fix acl for parsing wrong command on ( num matches ) data

---

changelogs/fragments/492-snmp-fact-view-key-correction
changelogs/fragments/492-snmp-fact-view-key-correction.yaml
plugins/module_utils/network/ios/rm_templates/snmp_server.py

Fix incorrect key name that causes snmp server fact collection to fail whenever a view is defined in the config.
Fix #491 
`rm_templates.snmp_server.Snmp_serverTemplate`
```paste below
```

Update result to add views in facts for snmp_server.py

---

changelogs/fragments/reflexive_acls_fix.yaml
plugins/module_utils/network/ios/facts/acls/acls.py
plugins/module_utils/network/ios/rm_templates/acls.py
tests/unit/modules/network/ios/test_ios_acls.py

filter out reflexive acls from facts, as they are dynamically generated over certain versions of IOS.
The presence of the ACLs causes wrong rendering of the facts.
ios_acls
```paste below
```

filter out reflexive acls from facts

---

changelogs/fragments/legacy_base_lineprotocol.yml
plugins/module_utils/network/ios/facts/legacy/base.py
tests/unit/modules/network/ios/fixtures/ios_facts_show_interfaces
tests/unit/modules/network/ios/test_ios_facts.py

line protocol option was unable to get extracted due to the operational state in interface details
`TenGigabitEthernet2/5/5 is down, line protocol is down (notconnect)`
also matches
`GigabitEthernet0/2 is administratively down, line protocol is down`
ios_facts [legacy]
```paste below
```

[ios_facts] Line protocol option regex update in legacy facts gathering

---

changelogs/fragments/fix_become_with_exec_prompt_timestamp.yml
plugins/terminal/ios.py

Fix become raises error when exec prompt timestamp is configured

---

changelogs/fragments/acl_proto_options_fix.yml
plugins/module_utils/network/ios/rm_templates/acls.py

**This is a redo of #516 as I messed up the repo while updating it to the latest code base.**
Check if proto_options is actually a dictionary instead of simply checking if it exists.
This fixes the error `AttributeError: 'bool' object has no attribute 'keys'`, which is a result of simply checking if proto_options exists, rather than making sure it is actually a dictionary.
Adding protocol_options to every entry isn't an option as that results in `Unsupported attribute for standard ACL - protocol_options.`
ios_acls
An example task that results in the error would be
```
- name: CISCO | IOS | Deploying ACL template
cisco.ios.ios_acls:
state: overridden
config:
- afi: ipv4
acls:
- name: TEST_ACL
acl_type: extended
aces:
- sequence: 10
grant: permit
protocol_options:
udp: …
```

[ios_acls] Fix AttributeError on dictionary check

---

changelogs/fragments/acl_550.yaml
plugins/module_utils/network/ios/facts/acls/acls.py
tests/unit/modules/network/ios/test_ios_acls.py

Handle ACL config parsing when match/matches are present.
Turns out the appliance is good with grammar as it says `match` when the matching count is _1_ and `matches` when it is more than 1
ios_acls
```paste below
```

[acls] Handle ACL config parsing when match/matches are present

---

changelogs/fragments/bug_fix_ntp.yaml
plugins/modules/ios_ntp.py

NTP fix to handle server attributes gracefully on no match
ios_ntp
```paste below
```

[ntp] fix to handle server attributes gracefully on no match

---

changelogs/fragments/fix_route_maps_618.yml
plugins/module_utils/network/ios/rm_templates/route_maps.py

fix parsers failing on tailing white space on config
ios_route_maps
```paste below
```

[route_maps] fix parsers failing on tailing white space on config

---

README.md
changelogs/fragments/docs_and_operatingstate.yaml
docs/cisco.ios.ios_command_module.rst
docs/cisco.ios.ios_facts_module.rst
plugins/module_utils/network/ios/facts/legacy/base.py
plugins/modules/ios_command.py
plugins/modules/ios_facts.py
tests/unit/modules/network/ios/test_ios_facts.py

facts to show operating state of the device 
older IOS versions without Operation state
```paste below
ok: [abc] => {
"ansible_facts": {
"ansible_net_api": "cliconf",
"ansible_net_gather_network_resources": [],
"ansible_net_gather_subset": [
"default"
],
"ansible_net_hostname": "testme",
"ansible_net_image": "flash0:/vios_l2-adventerprisek9-m",
"ansible_net_iostype": "IOS",
"ansible_net_model": "IOSv",
"ansible_net_operatingmode": "autonomous",
"ansible_net_python_version": "3.10.8",
"ansible_net_serialnum": "9BB7BJD12FA",
"ansible_net_system": "ios",
"ansible_net_version": "15.2(20170321:233949)",
"ansible_network_resources": {}
},
"changed": false,
"invocation": {
"module_args": {
"available_network_resources": false, …
```

[facts] - facts to show operating state of the appliance

---

changelogs/fragments/692-fix-community-issues.yaml
changelogs/fragments/708-fix-interface-vrf-assignment.yaml
changelogs/fragments/717_acls_bug_fix.yaml
docs/cisco.ios.ios_acls_module.rst
plugins/module_utils/network/ios/argspec/acls/acls.py
plugins/module_utils/network/ios/rm_templates/acls.py
plugins/modules/ios_acls.py
tests/integration/targets/ios_acl_interfaces/tests/cli/_populate_config.yaml
tests/integration/targets/ios_acls/tests/cli/_remove_config.yaml
tests/unit/modules/network/ios/test_ios_acls.py

fix precedence type for ace 
argspec had it as int but it never generated int in the config hence facts.
- 
ios_acls
```paste below
"ansible_network_resources": {
"acls": [
{
"acls": [
{
"aces": [
{
"grant": "deny",
"sequence": 10,
"source": {
"address": "192.168.1.0",
"wildcard_bits": "0.0.0.255"
}
},
{
"grant": "deny",
"sequence": 20,
"source": {
"address": "192.168.2.0",
"wildcard_bits": "0.0.0.255"
}
}
],
"acl_type": "standard",
"name": "std_acl"
},
{
"aces": [
{
"destination": {
"any": true
},
"grant": "permit",
"precedence": "internet",
"protocol": "ip",
"sequence": 10,
"source": {
"any": true
}
}
],
"acl_type": "extended",
"name": "test_perecedece"
}
],
"afi": "ipv4"
},
```

[acls] fix precedence type for ace

---

changelogs/fragments/ospf_interface_minimal.yaml
plugins/module_utils/network/ios/rm_templates/ospf_interfaces.py
tests/unit/modules/network/ios/test_ios_ospf_interfaces.py

fix ospf interfaces on the configuration of dead-interval,  wrong facts generated when hello-multiplier is configured
ios_ospf_interfaces 
```paste below
```

[ospf_interfaces], fix wrong facts generation when hello-multiplier is configured

---

changelogs/fragments/ospfv2_module_docfix.yml
docs/cisco.ios.ios_ospfv2_module.rst
plugins/modules/ios_ospfv2.py

The `config.processes.network` parameter  in EXAMPLES from:
```yaml
network:
address: 198.51.100.0
wildcard_bits: 0.0.0.255
area: 5
```
To a list representation
```yaml
network:
- address: 198.51.100.0
wildcard_bits: 0.0.0.255
area: 5
```
`cisco.ios.ios_ospfv2` module

fixed documentation in ospfv2 network parameter EXAMPLES

---

changelogs/fragments/interface_mode.yaml
docs/cisco.ios.ios_interfaces_module.rst
plugins/module_utils/network/ios/argspec/interfaces/interfaces.py
plugins/module_utils/network/ios/config/interfaces/interfaces.py
plugins/module_utils/network/ios/rm_templates/interfaces.py
plugins/modules/ios_interfaces.py
tests/unit/modules/network/ios/test_ios_interfaces.py

add mode to attribute to ios_interfaces
-  Manage Layer2 or Layer3 state of the interface.
-  For a Layer 2 appliance mode Layer2 adds switchport command ( default impacts idempotency).
-  For a Layer 2 appliance mode Layer3 adds no switchport command.
-  For a Layer 3 appliance mode Layer3/2 has no impact rather produces command fails.
ios_interfaces
```paste below
PLAYBOOK 
-------------------------------------------------------------------------------
tasks:
- name: Merge provided configuration with device configuration check mode
cisco.ios.ios_interfaces:
config:
- name: GigabitEthernet2
description: Configured and Merged by Ansible Network
enabled: true
mode: layer2
- name: GigabitEthernet3
description: Configured and Merged by Ansible Network
mode: layer3 …
```

[ios_interfaces] add mode to ios_interfaces

---

.github/workflows/codecoverage.yml
.github/workflows/tests.yml
changelogs/fragments/codecov_workfow_fix.yml

Fixed workflow be moving the codecoverage to different file since github.head_ref variable does not appear during the push github event
- Codecoverage
- `.github/workflows/codecoverage.yml`

Fixed codecov workflow

---

changelogs/fragments/fix_acls_rendering_mac.yaml
plugins/module_utils/network/ios/rm_templates/acls.py
tests/unit/modules/network/ios/test_ios_acls.py

Prevent rendering of mac based access-lists in facts
ios_acls
```paste below
```

[ios_acls] prevent rendering of mac access-lists in facts

---

changelogs/fragments/bgp_global_timer_render.yml
galaxy.yml
plugins/module_utils/network/ios/config/bgp_global/bgp_global.py
plugins/module_utils/network/ios/rm_templates/bgp_global.py
tests/unit/modules/network/ios/test_ios_bgp_global.py

render correct configuration for timers under neighbours
```paste below
- name: "Configure BGP Global"
cisco.ios.ios_bgp_global:
config:
as_number: '65000'
timers:
holdtime: 30
bgp:
log_neighbor_changes: true
router_id:
address: 10.2.1.1
neighbors:
- neighbor_address: 10.254.1.2
remote_as: '65000'
timers:
holdtime: 30
interval: 10
```

[bgp_global] render correct configuration for timers under neighbor

---

changelogs/fragments/ios_interface_templates
changelogs/fragments/ios_interface_templates.yml
docs/cisco.ios.ios_interfaces_module.rst
galaxy.yml
plugins/module_utils/network/ios/argspec/interfaces/interfaces.py
plugins/module_utils/network/ios/config/interfaces/interfaces.py
plugins/module_utils/network/ios/rm_templates/interfaces.py
plugins/modules/ios_interfaces.py
tests/unit/modules/network/ios/test_ios_interfaces.py

This does not support direct templating. Instead this is support for IOS's built in templating engine and static assignment of templates introduced in 15.2E. https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/ibns/configuration/15-e/ibns-15-e-book/ibns-int-temp.html
This is related to a previous issue I raised #677 
cisco.ios.interfaces
Example Ansible Task
```
- name: Apply Employee Templates to Ports
cisco.ios.ios_interfaces:
config:
- name: GigabitEthernet0/1
template: EMPLOYEE_TEMPLATE
- name: GigabitEthernet0/2
template: EMPLOYEE_TEMPLATE
- name: GigabitEthernet0/3
template: EMPLOYEE_TEMPLATE
state: replaced  
```
Example Result on Switch
```
interface GigabitEthernet0/1
!
interface GigabitEthernet0/2
!
interface GigabitEthernet0/3
!
interface GigabitEthernet0/1 …
```

IOS Interface Template Support

---

changelogs/fragments/snmp_user_bug.yml
plugins/module_utils/network/ios/facts/snmp_server/snmp_server.py
plugins/terminal/ios.py
tests/integration/targets/ios_snmp_server/tests/cli/_populate_config.yaml
tests/integration/targets/ios_snmp_server/tests/cli/_remove_config.yaml

The command `show snmp user` gives stderror - `%SNMP agent not enabled` when the snmp agent is not enabled
This PR aims to fix the above issue but handling the error
- `facts/snmp_server.py`

SNMP user error fix

---

changelogs/fragments/cpu_util.yml
docs/cisco.ios.ios_facts_module.rst
plugins/modules/ios_facts.py

This PR adds `ansible_net_cpu_utilization`, which was introduced in #816, to the docs of `ios_facts`.
`ios_facts`
None.

Add `ansible_net_cpu_utilization` to `ios_facts` docs

---

changelogs/fragments/bug_ios_service-private_config_encryption.yml
plugins/module_utils/network/ios/config/service/service.py
tests/unit/modules/network/ios/test_ios_service.py

Fix bug #910 
Add a conditionnal where private_config_encryption is set to `True` for default value only if present in haved configution

ios_service - Bug with private-config-encryption

---

changelogs/fragments/fix_ospfv2_integration_test.yml
tests/integration/targets/ios_ospfv2/tests/cli/_initial_vrf_setup.yaml

Address the issue of encountering an unexpected module failure related to invalid input while attempting to run iOS OSPFv2 integration tests from the Controller with the EE container.
fixes: #928 

Fix ospfv2 integration test issues

---

changelogs/fragments/bgp_add_fam_route_maps.yaml
docs/cisco.ios.ios_bgp_address_family_module.rst
plugins/module_utils/network/ios/argspec/bgp_address_family/bgp_address_family.py
plugins/module_utils/network/ios/config/bgp_address_family/bgp_address_family.py
plugins/modules/ios_bgp_address_family.py
tests/unit/modules/network/ios/test_ios_bgp_address_family.py

This should go by a deprecation cycle and a new attribute needs to be introduced here as str
Keeping the options in draft.
bgp_address_family
```paste below
```

[bgp_address_family] fix remote_as 

---

changelogs/fragments/bgp_global_evpn_fix.yml
plugins/module_utils/network/ios/facts/bgp_global/bgp_global.py

remote_as not mandatory for neighbors
ios_bgp_global
Configuration reference from a l2 appliance.
```paste below
router bgp 65001
template peer-policy LEAF-EVPN-PEER-POLICY
send-community both
exit-peer-policy
!
template peer-policy SPINE-EVPN-PEER-POLICY
route-reflector-client
send-community both
exit-peer-policy
!
template peer-session EVPN-PEER-SESSION
remote-as 65001
update-source Loopback0
exit-peer-session
!
bgp router-id 172.16.255.14
bgp log-neighbor-changes
no bgp default ipv4-unicast
neighbor 172.16.255.3 remote-as 100
neighbor 172.16.255.3 inherit peer-session EVPN-PEER-SESSION
neighbor 172.16.255.4 remote-as 101
neighbor 172.16.255.4 inherit peer-session EVPN-PEER-SESSION
!
address-family ipv4
exit-address-family
!
address-family l2vpn evpn
neighbor …
```

remote_as not mandatory for neighbors

---

changelogs/fragments/fix_acls_old.yml
plugins/module_utils/network/ios/rm_templates/acls.py

The collection supports cisco ios xe 17.x 
The acls facts are processed on the basis of the `show running-config | section access-list` command
The command is updated replacing `show access-lists` command in order to incorporate the functionality of remarks, as native IOS XE supports it with the ios_acls module. 
In an older EOL'd version of ios 15.x, the command does not render any sequence number,  essential for the module to process.
If support for older iosxe versions are needed it is advised to use cisco.ios 5.1.0
```
host15v#show running-config | section access-list
ip access-list standard SNMP_sec
permit 10.255.236.0 0.0.3.255
```
In a supported appliance version, ios xe 17.x
```
foo#show running-config | section access-list
ip access-list standard SNMP-sec
10 permit 10.255.236.0 …
```

ios_acls - make sequence optional for rendering of standard acls.

---

changelogs/fragments/ios_facts_tests.yml
tests/unit/modules/network/ios/fixtures/ios_facts_show_interfaces
tests/unit/modules/network/ios/test_ios_facts.py

This unit test aim to verify sub-interface index name greater than 999.
(For example: GigabitEthernet0/0/0.1012)
Addresses issue : #972 
- Test

ios_facts test verify sub-interface index > 999

---

changelogs/fragments/snmp_server_ipv6_acl.yml
plugins/module_utils/network/ios/rm_templates/snmp_server.py
tests/unit/modules/network/ios/test_ios_snmp_server.py

Fixes #993 
The `group` and `user` IPv6 `access` entries are incorrectly generated and/or parsed, like:
```
snmp-server group read-only-group v3 priv read read-all-view access snmp-ipv4-acl access ipv6 snmp-ipv6-acl
```
->
```
snmp-server group read-only-group v3 priv read read-all-view access ipv6 snmp-ipv6-acl snmp-ipv4-acl
```
I added test cases for `group` and `user` commands.
ios_snmp_server

Fix #993 - user and group IPv6 ACLs

---

changelogs/fragments/ios_l3_ipv6.yml
plugins/module_utils/network/ios/config/l3_interfaces/l3_interfaces.py
plugins/module_utils/network/ios/utils/utils.py
tests/unit/modules/network/ios/test_ios_l3_interfaces.py

Remove strict ipv6 validation
l3_interfaces
playbook
```paste below
- name: SET VIRTUAL PORT GROUP
cisco.ios.ios_l3_interfaces:
config:
- name: VirtualPortGroup0
ipv4:
- address: "10.0.2.x/24"
ipv6:
- address: "fe80:0:cxc:84::4"
link_local: true
state: merged
```
output
```paste below
[
"interface VirtualPortGroup0",
"ip address 10.0.2.x 255.255.255.0",
"ipv6 address fe80:0:cxc:84::4 link-local"
],
"invocation": {
"module_args": {
"config": [
```

[ios_l3_interfaces] Remove strict ipv6 validation

---

changelogs/changelog.yaml
changelogs/config.yaml
changelogs/fragments/ios_user_int_test.yml
tests/integration/targets/ios_facts/tests/cli/all_facts.yaml
tests/integration/targets/ios_user/tests/cli/basic.yaml

- Replaced the hash which was being used to test type 5 secret.
- Changed loop logic for a task to include loop_control to fix error - The loop variable
'item' is already in use.
- Test fix

Integration test fix for ios_user and ios_facts

---

changelogs/fragments/acl_refactor.yaml
docs/cisco.ios.ios_acls_module.rst
plugins/module_utils/network/ios/config/acls/acls.py
plugins/module_utils/network/ios/facts/acls/acls.py
plugins/module_utils/network/ios/rm_templates/acls.py
plugins/modules/ios_acls.py
tests/integration/targets/ios_acls/tests/cli/remarks_states.yaml
tests/integration/targets/ios_acls/vars/main.yaml
tests/unit/modules/network/ios/test_ios_acls.py

The module now treats all the remarks for each ace as a block.
1. every time a remark for an ace (with sequence) is updated the module would remove all the remarks for that ace entry by `no <sequence> remark`  and add all the remarks back, as it is the only possible way to preserve the remarks order.
2. Whenever an ace entry is updated it is removed first, which removes all the subordinate remarks. So we explicitly add the remarks back to maintain consistency and add back the ace entry.
3. There is no line-by-line deletion of remarks entries, for every negation-specific action state remarks are removed as a whole and then added back. 
ios_acls
```paste below
```

[ios_acls] add fix to standalone remarks

---

changelogs/fragments/l3_sinterface_parser.yml
plugins/module_utils/network/ios/rm_templates/l3_interfaces.py
tests/unit/modules/network/ios/test_ios_l3_interfaces.py

This fixes issue where the module is gathering wrong facts for source_interface in ipv4 in l3_interfaces.
It was gathering a `bool` value instead of the name of the interface which should be `str` based on the argspec.
- tests/unit/modules/network/ios/test_ios_l3_interfaces.py
- plugins/module_utils/network/ios/rm_templates/l3_interfaces.py

l3_interfaces - Fix gathering wrong facts for source interface in ipv4.

---

changelogs/fragments/ios_service_fix.yml
docs/cisco.ios.ios_service_module.rst
plugins/module_utils/network/ios/argspec/service/service.py
plugins/module_utils/network/ios/config/service/service.py
plugins/module_utils/network/ios/facts/service/service.py
plugins/module_utils/network/ios/rm_templates/service.py
plugins/modules/ios_service.py
tests/unit/modules/network/ios/test_ios_service.py

- ios_service - Fix timestamps attribute, to generate right configuration.
- ios_service - Add tcp_small_servers and udp_small_servers attributes, to generate configuration.
ios_service
```paste below
```

fix ios_service issues

---

changelogs/fragments/snmp_server_host.yml
plugins/module_utils/network/ios/rm_templates/snmp_server.py
tests/unit/modules/network/ios/test_ios_snmp_server.py

Fixes issue - #1071 
cisco.ios.ios_snmp_server module is NOT applying commands correctly, so causing errors.
The correct way this command should be applied is:
`snmp-server host 10.1.1.1 vrf Mgmt-intf version 3 priv test_user`
But in the run the playbook it tries to run the command like this instead:
`snmp-server host 10.1.1.1 version 3 priv vrf Mgmt-intf test_user`
Fixed based on - cisco [docs](https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/snmp/command/nm-snmp-cr-book/nm-snmp-cr-s5.html#wp3482803949)
Syntax:
```
snmp-server host {hostname | ip-address} [vrf vrf-name | informs | traps | version {1 | 2c | 3 [auth | noauth | priv]}] community-string [udp-port port [notification-type] | notification-type] 
```

Fix snmp host syntax

---

changelogs/fragments/snmp_parse_fix.yml
plugins/module_utils/network/ios/rm_templates/snmp_server.py
tests/unit/modules/network/ios/test_ios_snmp_server.py

Fixes parsing of snmp server host config
#1073 - Changes the command of snmp host due to with parsing failed, fixed that in this pr

Fix snmp-server host commad parsing

---

changelogs/fragments/static_routes_facts_fix.yml
plugins/module_utils/network/ios/rm_templates/static_routes.py
tests/unit/modules/network/ios/test_ios_static_routes.py

Netmask is part of route destination and should be included as 'primary' key for distinguishing routes. For ipv6 it is already part of dest parameter.
Fixes https://github.com/ansible-collections/cisco.ios/issues/1037
```paste below
DEVICE BEFORE STATE:
#sh run | sec ip route
ip route 153.5.255.0 255.255.255.248 178.172.80.30
ip route 192.168.30.0 255.255.255.0 GigabitEthernet0/1.23 10.0.0.33 tag 30
ip route 192.168.30.0 255.255.255.0 10.0.0.3
ip route 192.168.30.0 255.255.255.248 GigabitEthernet0/1.23 10.0.0.33 tag 30
PLAYBOOK:
- name: Replace provided configuration with device configuration
ios_static_routes:
config:
- address_families:
- afi: ipv4
routes:
- dest: 153.5.255.0/29
next_hops:
- forward_router_address: 178.172.80.30
- dest: …
```

FIX: Include netmask into static_routes parser as part of result key

---

changelogs/fragments/ios_acls_udp.yml
plugins/module_utils/network/ios/config/acls/acls.py
tests/unit/modules/network/ios/test_ios_acls.py

acls rm maps port 135/udp to the protocol msrpc, which isn't a valid command for a UDP ACE.
Issue -
```
csr2(config)#ip access-list extended QOS-STAFF-AUTHENTICATION
csr2(config-ext-nacl)#20 permit udp any any eq msrpc
^
% Invalid input detected at '^' marker.
```
Below works -
```
csr2(config-ext-nacl)#20 permit udp any any eq 135
```
This PR aims to fix the above issue
- config/acls.py

Acls - fix incorrectly mapping of port 135/udp to msrpc

---

CHANGELOG.rst

Trivial Update CHANGELOG.rst

---

changelogs/fragments/pr-1095-fragment.yaml
plugins/module_utils/network/ios/rm_templates/bgp_global.py
plugins/module_utils/network/ios/rm_templates/static_routes.py
tests/unit/modules/network/ios/test_ios_bgp_global.py

Found some minor issues on static_routes not idempotent when TenGigabitEthernet Interfaces in use and
within the same troubleshooting fixing also ebgp-multihop recognition
static_routes
bgp_global
Add TenGigabitEthernet to interface regex to also recognize these type of interfaces in static routes.
Typo fixed and variable usage in bgp_global for ebgp-multihop

Fix some idempotency issues in static_routes and bgp_global

---

changelogs/fragments/1097-ios-facts-MiB.yml
docs/cisco.ios.ios_facts_module.rst
plugins/modules/ios_facts.py

Updated the documentation for the ansible_net_memtotal_mb and ansible_net_memfree_mb return values to have the acronym for mebibytes (MiB) instead of megabits (Mb). In the source code it seems to be converting the values reported by the Cisco device from bits to mebibytes.
ios_facts
The source code for finding the unit conversion can be found here:
https://github.com/ansible-collections/cisco.ios/blob/main/plugins/module_utils/network/ios/facts/legacy/base.py#L151
```

Update IOS Facts documentation to say mebibytes (MiB) instead of megabits (Mb)

---

changelogs/fragments/vlan_err_reg.yaml
plugins/terminal/ios.py

ios_vlans - Make the module fail when vlan name is longer than 32 characters with configurations as VTPv1 and VTPv2.
ios_vlans
```paste below
```

ios_vlans - add error regex for vlan name longer than 32 characters

---

changelogs/fragments/1101-typo-ios_service.yml
plugins/module_utils/network/ios/rm_templates/service.py
tests/unit/modules/network/ios/test_ios_service.py

Fix typo in ios_service module
ios_service
The actual command in Cisco IOS uses `msec` for *milliseconds*. I believe `mesc` is a typo.

Fix typo in ios_service module

---

changelogs/fragments/fix_interface_fifty_interface.yml
plugins/module_utils/network/ios/ios.py
plugins/module_utils/network/ios/utils/utils.py
tests/unit/modules/network/ios/test_ios_interfaces.py

Add support for `FiftyGigabitEthernet` as it was always being replaced by `FiveGigabitEthernet`
```yaml
- name: test
check_mode: true
cisco.ios.ios_interfaces:
config:
- name: FiftyGigE1/0/1
description: add support for FiftyGigabitEthernet
```
```
ios_interface
utils.py
l2_interface
l3_interface
lacp_interfaces
lldp_interfaces
```
```paste below
commands:
- interface FiftyGigabitEthernet1/0/1
- description NOENB-C9300-MGT04.dnbnor.no via TenGigabitEthernet1/1/2
- no shutdown
```

Add support for FiftyGigabitEthernet

---

changelogs/fragments/ios_static_routes.yaml
plugins/module_utils/network/ios/rm_templates/static_routes.py
tests/integration/targets/ios_static_routes/tests/cli/_parsed.cfg
tests/integration/targets/ios_static_routes/tests/cli/parsed.yaml
tests/integration/targets/ios_static_routes/vars/main.yaml
tests/unit/modules/network/ios/test_ios_static_routes.py

Fixes issue where data of `metric_distance` is being populated in `forward_router_address` when gathering facts.
Happens because the regex used for `forward_router_address` picks up the `metric_distance` value when the interface is present instead of `forward_router_address`

Fixes population of wrong data forward_router_address attribute

---

changelogs/fragments/bgp_global_render_pass.yml
plugins/module_utils/network/ios/rm_templates/bgp_address_family.py
plugins/module_utils/network/ios/rm_templates/bgp_global.py
tests/unit/modules/network/ios/test_ios_bgp_global.py

- ios_bgp_global - fix parsing of password_options while gathering password configuration from appliance.
- ios_bgp_address_family - fix parsing of password_options while gathering password configuration from appliance.
- 
ios_bgp_global
ios_bgp_address_family
```bash
router bgp 65000
bgp nopeerup-delay post-boot 10
bgp bestpath compare-routerid
bgp advertise-best-external
timers bgp 100 200 150
redistribute connected metric 10
neighbor 192.0.2.1 remote-as 100
neighbor 192.0.2.1 password 7 DEQPITOP101395
neighbor 192.0.2.1 route-map test-route out
address-family ipv4
neighbor 192.0.2.28 activate
neighbor 172.31.35.140 activate
```
Parses - 
```json
{
"as_number": "65000",
"bgp": {
"nopeerup_delay_options": {"post_boot": 10},
"bestpath_options": {"compare_routerid": …
```

[ios_bgp_global/ address_family] fix parsing of password_options while gathering password configuratin

---

changelogs/fragments/fix_ci_upstream.yaml
plugins/module_utils/network/ios/rm_templates/route_maps.py
tests/integration/targets/ios_interfaces/tests/cli/_populate_config.yaml
tests/integration/targets/ios_l3_interfaces/tests/cli/deleted.yaml
tests/integration/targets/ios_l3_interfaces/tests/cli/gathered.yaml
tests/integration/targets/ios_l3_interfaces/tests/cli/merged.yaml
tests/integration/targets/ios_l3_interfaces/tests/cli/overridden.yaml
tests/integration/targets/ios_l3_interfaces/tests/cli/replaced.yaml
tests/integration/targets/ios_l3_interfaces/vars/main.yaml
tests/integration/targets/ios_lldp_interfaces/tests/cli/_populate_config.yaml
tests/integration/targets/ios_lldp_interfaces/tests/cli/deleted.yaml
tests/integration/targets/ios_ospf_interfaces/tests/cli/gathered.yaml
tests/integration/targets/ios_ospf_interfaces/tests/cli/merged.yaml
tests/integration/targets/ios_ospf_interfaces/tests/cli/overridden.yaml
tests/integration/targets/ios_ospf_interfaces/tests/cli/replaced.yaml
tests/integration/targets/ios_ospf_interfaces/vars/main.yaml
tests/integration/targets/ios_route_maps/vars/main.yaml
tests/integration/targets/ios_user/tests/cli/basic.yaml
tests/unit/modules/network/ios/test_ios_route_maps.py

bugfixes:
- ios_route_maps - Fixes an issue where 'no description value' is an invalid command on the latest devices.
trivial:
- ios_lldp_interfaces - Fix upstream CI failure due to difference in interface values.
- ios_interfaces - Fix upstream CI failure due to difference in interface values.
- ios_user - Fixes ios_user purging the ssh user running the test.
- ios_ospf_interfaces - Fix upstream CI failure due to difference in interface values.
- Test fixes

Fix upstream CI

---

changelogs/fragments/fix_acls.yml
plugins/module_utils/network/ios/rm_templates/acls.py
tests/integration/targets/ios_l3_interfaces/tests/cli/_remove_config.yaml
tests/integration/targets/ios_vrf_interfaces/tests/common/_remove_config.yaml
tests/unit/modules/network/ios/test_ios_acls.py

Fix issues with the `cisco.ios.ios_acls` Ansible module when applying an acl. The module incorrectly parses certain ACL configuration attributes. The module also incorrectly generates certain commands, this PR aims to fix the above
- `ios_acls`
```yaml
running_config: |-
!
ip access-list extended CP_Quarantine-v4-in
10 permit udp any object-group FAA-Networks eq bootps
20 permit object-group BT-ports any object-group AIT-BT-Servers
30 permit tcp any object-group CP-Appliances eq 443
40 deny   object-group deny-mgmt-ports any any
50 permit object-group icmp any object-group IB-Servers
60 permit object-group generic-any-port any object-group IB-Servers
70 permit object-group generic-any-port any object-group AD-Servers
80 permit object-group generic-any-port any …
```

Fix wrong parsing of commands and wrong command generation
